#!/usr/bin/env bash
# H3 acceptance test: hematite regenerates this fixture byte-for-byte, and the
# regenerated composition builds and runs. Run from the repo root.
set -euo pipefail
cd "$(dirname "$0")/../../.."   # repo root
FIX=tests/golden/two-component

cargo build --release -q
./target/release/hematite compose "$FIX"

# 1. Byte-for-byte: composing again must reproduce the reviewed output.
#
# The baseline is `golden/`, a snapshot of the composition committed as test
# DATA. It used to be the generated files themselves, sitting in this fixture
# and committed — which stopped being possible when a world started composing
# into `target/hematite/<world>` (D-H7-38), and was never a good baseline
# anyway: a fixture could pass against stale output nobody had regenerated.
G="$FIX/golden"; O="$FIX/target/hematite/two-component"
for rel in platform/main.roc Cargo.toml abi/Cargo.toml abi/src/lib.rs \
           components/cli/Cargo.toml components/cli/src/lib.rs; do
  if ! diff -q "$G/$rel" "$O/$rel" >/dev/null; then
    echo "FAIL: regenerated $rel differs from the reviewed golden:"
    diff "$G/$rel" "$O/$rel" || true
    echo "(if the change is intended: cp \"$O/$rel\" \"$G/$rel\")"
    exit 1
  fi
done
echo "ok: regenerated byte-for-byte identical to golden"

# 2. The regenerated composition builds and runs.
if ! _b=$(./target/release/hematite build "$FIX" --app app --out reader 2>&1); then echo "FAIL: build reader" >&2; echo "$_b" >&2; exit 1; fi
out=$("$FIX/target/hematite/two-component/bin/reader" "$FIX/target/hematite/two-component/platform/main.roc")
expected="$(wc -l < "$FIX/target/hematite/two-component/platform/main.roc" | tr -d ' ') lines in $FIX/target/hematite/two-component/platform/main.roc"
if [[ "$out" != "$expected" ]]; then
  echo "FAIL: expected '$expected', got '$out'"; exit 1
fi
echo "ok: composed platform runs — $out"
echo "H3 PASS"
