#!/usr/bin/env bash
# H3 acceptance test: hematite regenerates this fixture byte-for-byte, and the
# regenerated composition builds and runs. Run from the repo root.
set -euo pipefail
cd "$(dirname "$0")/../../.."   # repo root
FIX=tests/golden/two-component

cargo build --release -q
./target/release/hematite compose "$FIX"

# 1. Byte-for-byte: the committed generated files must be unchanged.
if ! git diff --quiet -- \
     "$FIX/platform/main.roc" "$FIX/Cargo.toml" \
     "$FIX/components/cli/Cargo.toml" "$FIX/components/cli/src/lib.rs" \
     "$FIX/abi/Cargo.toml" "$FIX/abi/src/lib.rs"; then
  echo "FAIL: regenerated output differs from committed golden:"
  git --no-pager diff -- "$FIX/platform/main.roc" "$FIX/components/cli/src/lib.rs"
  exit 1
fi
echo "ok: regenerated byte-for-byte identical to golden"

# 2. The regenerated composition builds and runs.
if ! _b=$(./target/release/hematite build "$FIX" --app app --out reader 2>&1); then echo "FAIL: build reader" >&2; echo "$_b" >&2; exit 1; fi
out=$("$FIX/bin/reader" "$FIX/platform/main.roc")
expected="$(wc -l < "$FIX/platform/main.roc" | tr -d ' ') lines in $FIX/platform/main.roc"
if [[ "$out" != "$expected" ]]; then
  echo "FAIL: expected '$expected', got '$out'"; exit 1
fi
echo "ok: composed platform runs — $out"
echo "H3 PASS"
