#!/usr/bin/env bash
# H4 acceptance: the Roc-shim (memfs) composition regenerates byte-for-byte,
# Path.roc is identical to the host-fs fixture, and it builds and runs -- a
# successful read also proves the cell round-trip (memfs asserts put!==get!).
set -euo pipefail
cd "$(dirname "$0")/../../.."   # repo root
FIX=tests/golden/roc-shim

cargo build --release -q
./target/release/hematite compose "$FIX"

# Path.roc byte-identical across the host-fs and Roc-fs wirings (the substitution proof).
if ! diff -q tests/golden/two-component/components/pathlib/Path.roc "$FIX/components/pathlib/Path.roc" >/dev/null; then
  echo "FAIL: Path.roc differs between host-fs and roc-fs fixtures"; exit 1
fi
echo "ok: Path.roc byte-identical across host-fs and Roc-shim wirings"

if ! git diff --quiet -- "$FIX/platform/main.roc" "$FIX/Cargo.toml" \
     "$FIX/components/cli/src/lib.rs" "$FIX/abi/src/lib.rs"; then
  echo "FAIL: regenerated output differs from committed golden"
  git --no-pager diff -- "$FIX/platform/main.roc"; exit 1
fi
echo "ok: regenerated byte-for-byte identical to golden"

if ! _b=$(./target/release/hematite build "$FIX" --app app --out reader 2>&1); then echo "FAIL: build reader" >&2; echo "$_b" >&2; exit 1; fi
out=$("$FIX/bin/reader" hello.txt)
if [[ "$out" != "3 lines in hello.txt" ]]; then
  echo "FAIL: expected '3 lines in hello.txt', got '$out'"; exit 1
fi
echo "ok: Roc-shim fs + cell round-trip run — $out"
echo "H4 PASS"
