// GENERATED BY hematite — do not edit. Regenerate with `hematite compose`.
//! The one ABI crate (D4/D10): `roc glue` output (generated.rs) plus this thin
//! wrapper. Exactly one per composition; every component host depends on it.
#![allow(dead_code, non_camel_case_types, improper_ctypes, improper_ctypes_definitions, unexpected_cfgs)]
mod generated;
pub use generated::*;

use std::sync::OnceLock;

unsafe impl Sync for RocHost {}
unsafe impl Send for RocHost {}

static HOST: OnceLock<RocHost> = OnceLock::new();

/// The process-wide RocHost (default allocators/handlers over the linker
/// runtime symbols). Cached; used to build owned Roc values.
pub fn host() -> &'static RocHost {
    HOST.get_or_init(|| make_roc_host(std::ptr::null_mut()))
}
