// GENERATED BY hematite — do not edit. Regenerate with `hematite compose`.
//! The service contract shim (D-H7-7): the driver's view of every service
//! component in this world. See hematite's src/services.rs for the shape.
use super::*;
use core::ffi::c_void;
use core::mem::ManuallyDrop;
use std::sync::OnceLock;

/// D8's `HostCtx`: what the driver hands each component at `init`.
#[repr(C)]
pub struct HostCtx {
    pub component_id: u32,
    /// Callable from any thread; the token is component-owned (D9) and comes
    /// back to the component through `complete` on the runtime thread.
    pub wake: extern "C" fn(u32, *mut c_void),
}

/// A synchronous answer to a wrapper command, in the component's own event type.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Answer<E: Copy> {
    pub route_key: RocStr,
    pub event: E,
}

/// What `complete` returns for a token the component woke the driver with.
#[repr(C)]
pub struct Completion<E> {
    pub request: u64,
    pub route_key: RocStr,
    pub event: E,
}

static WAKE: OnceLock<fn(u32, *mut c_void)> = OnceLock::new();

/// The one `wake` every component is handed: forwards to the driver's loop.
extern "C" fn courier(component_id: u32, token: *mut c_void) {
    if let Some(f) = WAKE.get() {
        f(component_id, token);
    }
}

pub const ECHO_ID: u32 = 1;
static CTX_ECHO: HostCtx = HostCtx { component_id: 1, wake: courier };
unsafe extern "C-unwind" {
    fn hematite__svc_echo__init(ctx: *const HostCtx);
    fn hematite__svc_echo__cmd(request: u64, route_key: RocStr, cmd: Echo) -> RocList<Answer<EchoEvent>>;
    fn hematite__svc_echo__complete(token: *mut c_void) -> Completion<EchoEvent>;
    fn hematite__svc_echo__gate(name: RocStr, argv: RocList<RocStr>) -> i32;
}

pub const TICK_ID: u32 = 2;
static CTX_TICK: HostCtx = HostCtx { component_id: 2, wake: courier };
unsafe extern "C-unwind" {
    fn hematite__svc_tick__init(ctx: *const HostCtx);
    fn hematite__svc_tick__cmd(request: u64, route_key: RocStr, cmd: Tick) -> RocList<Answer<TickEvent>>;
    fn hematite__svc_tick__complete(token: *mut c_void) -> Completion<TickEvent>;
    fn hematite__svc_tick__env() -> TickEnv;
    fn hematite__svc_tick__gate(name: RocStr, argv: RocList<RocStr>) -> i32;
}

/// Install the driver's wake sink and hand every component its `HostCtx`.
/// Call once, before the first drain.
pub fn init(wake: fn(u32, *mut c_void)) {
    let _ = WAKE.set(wake);
    unsafe {
        hematite__svc_echo__init(&CTX_ECHO);
        hematite__svc_tick__init(&CTX_TICK);
    }
}

/// Dispatch one drained command to its service. `None` for a core variant
/// (the driver handles those itself; the payload is untouched). Otherwise
/// the payload is MOVED to the component and its answers come back routed:
/// (route_key, event) pairs the driver feeds to `route`.
pub fn dispatch(cmd: &mut Cmd, request: u64, route_key: &str) -> Option<Vec<(RocStr, Event)>> {
    let host = host();
    match cmd.tag {
        CmdTag::Echo => {
            let payload = unsafe { cmd.take_payload_echo_unchecked() };
            let key = RocStr::from_str(route_key, host);
            let answers = unsafe { hematite__svc_echo__cmd(request, key, payload) };
            let mut out = Vec::with_capacity(answers.len());
            for a in answers.as_slice() {
                out.push((a.route_key, Event { payload: EventPayload { echo: ManuallyDrop::new(a.event) }, tag: EventTag::Echo }));
            }
            unsafe { answers.decref(host) }; // shallow: each answer was copied out
            Some(out)
        }
        CmdTag::Tick => {
            let payload = unsafe { cmd.take_payload_tick_unchecked() };
            let key = RocStr::from_str(route_key, host);
            let answers = unsafe { hematite__svc_tick__cmd(request, key, payload) };
            let mut out = Vec::with_capacity(answers.len());
            for a in answers.as_slice() {
                out.push((a.route_key, Event { payload: EventPayload { tick: ManuallyDrop::new(a.event) }, tag: EventTag::Tick }));
            }
            unsafe { answers.decref(host) }; // shallow: each answer was copied out
            Some(out)
        }
        #[allow(unreachable_patterns)]
        _ => None,
    }
}

/// The runtime-thread half of a wake (D9): the component turns its token
/// into a Roc event; the shim wraps it. `None` for an unknown component id.
pub fn on_wake(component_id: u32, token: *mut c_void) -> Option<(u64, RocStr, Event)> {
    match component_id {
        ECHO_ID => {
            let c = unsafe { hematite__svc_echo__complete(token) };
            Some((c.request, c.route_key, Event { payload: EventPayload { echo: ManuallyDrop::new(c.event) }, tag: EventTag::Echo }))
        }
        TICK_ID => {
            let c = unsafe { hematite__svc_tick__complete(token) };
            Some((c.request, c.route_key, Event { payload: EventPayload { tick: ManuallyDrop::new(c.event) }, tag: EventTag::Tick }))
        }
        _ => None,
    }
}

/// `TickEnv`: the `tick` block of `Env`, read once per frame.
pub fn env_tick() -> TickEnv {
    unsafe { hematite__svc_tick__env() }
}

/// The gate chain (D-H7-8): ask every component before the driver's own
/// arms. `Some(rc)` from the first component that claims `name`.
pub fn gate(name: &str, argv: &[String]) -> Option<i32> {
    let host = host();
    let gates: [unsafe extern "C-unwind" fn(RocStr, RocList<RocStr>) -> i32; 2] = [
        hematite__svc_echo__gate,
        hematite__svc_tick__gate,
    ];
    for g in gates {
        let args: Vec<RocStr> = argv.iter().map(|a| RocStr::from_str(a, host)).collect();
        let list = unsafe { RocList::from_slice(&args, host) };
        let rc = unsafe { g(RocStr::from_str(name, host), list) };
        if rc != -1 {
            return Some(rc);
        }
    }
    None
}
