// GENERATED BY hematite — do not edit. Regenerate with `hematite compose`.
//! Build a glue tag-union value from its payload and tag, on either pointer
//! width. See hematite's src/codegen.rs (`TAGGED_RS`).

/// # Safety
/// `T` must be the payload type glue associates with the variant `tag` sets;
/// the wrong one writes a well-formed value of the wrong variant. Size and
/// alignment are asserted rather than documented.
pub unsafe fn build<U, T>(tag: impl FnOnce(&mut U), payload: T) -> U {
    assert!(core::mem::size_of::<T>() <= core::mem::size_of::<U>(), "payload does not fit its tag union");
    assert!(core::mem::align_of::<T>() <= core::mem::align_of::<U>(), "payload over-aligned for its tag union");
    let mut u = core::mem::MaybeUninit::<U>::zeroed();
    // SAFETY: `U` is `#[repr(C)]` with its payload at offset 0 on both widths;
    // zeroed first so padding and any unwritten tail are defined.
    unsafe {
        core::ptr::write(u.as_mut_ptr() as *mut T, payload);
        let mut v = u.assume_init();
        tag(&mut v);
        v
    }
}
