// GENERATED BY hematite — do not edit. Regenerate with `hematite compose`.
//! The one ABI crate (D4/D10): `roc glue` output (generated.rs) plus this thin
//! wrapper. Exactly one per composition; every component host depends on it.
#![allow(dead_code, non_camel_case_types, improper_ctypes, improper_ctypes_definitions, unexpected_cfgs)]
mod generated;
pub use generated::*;

use std::sync::OnceLock;

unsafe impl Sync for RocHost {}
unsafe impl Send for RocHost {}

static HOST: OnceLock<RocHost> = OnceLock::new();

/// The process-wide RocHost (default allocators/handlers over the linker
/// runtime symbols). Cached; used to build owned Roc values.
pub fn host() -> &'static RocHost {
    HOST.get_or_init(|| {
        // Route the allocator hooks through the env-gated gauge so host-built
        // Roc values (RocStr::from_str, allocate_box) are counted alongside
        // Roc-initiated allocations (which enter via the driver's roc_alloc
        // symbol). Inert unless HEMATITE_ALLOC_GAUGE is set.
        let mut h = make_roc_host(std::ptr::null_mut());
        h.roc_alloc = gauge::roc_alloc;
        h.roc_dealloc = gauge::roc_dealloc;
        h
    })
}

/// Env-gated allocation gauge (test-only): counts Roc allocations vs frees so a
/// verify script can assert drop-balance for refcounted DATA (RocStr/RocList) --
/// the leaks the resource `live()` count cannot see. Every Roc allocation
/// funnels through `DefaultAllocators::roc_alloc`, whether Roc-initiated (the
/// driver's `roc_alloc` symbol) or host-initiated (the RocHost fn pointer), and
/// both are wired here, so the balance is complete. Zero counting cost unless
/// HEMATITE_ALLOC_GAUGE is set (the hooks still delegate, adding only a cached
/// bool check and one relaxed atomic when enabled). `roc_realloc` is a resize,
/// not a net alloc/free, so it is deliberately not counted.
pub mod gauge {
    use super::*;
    use core::ffi::c_void;
    use core::sync::atomic::{AtomicU64, Ordering};
    use std::sync::OnceLock;

    static ENABLED: OnceLock<bool> = OnceLock::new();
    static ALLOCS: AtomicU64 = AtomicU64::new(0);
    static DEALLOCS: AtomicU64 = AtomicU64::new(0);

    #[inline]
    fn on() -> bool {
        *ENABLED.get_or_init(|| std::env::var_os("HEMATITE_ALLOC_GAUGE").is_some())
    }

    #[inline]
    pub extern "C" fn roc_alloc(host: *mut RocHost, length: usize, alignment: usize) -> *mut c_void {
        if on() { ALLOCS.fetch_add(1, Ordering::Relaxed); }
        DefaultAllocators::roc_alloc(host, length, alignment)
    }
    #[inline]
    pub extern "C" fn roc_dealloc(host: *mut RocHost, ptr: *mut c_void, alignment: usize) {
        if on() { DEALLOCS.fetch_add(1, Ordering::Relaxed); }
        DefaultAllocators::roc_dealloc(host, ptr, alignment)
    }

    /// Roc allocations still live (allocs - deallocs); 0 at a clean exit.
    pub fn live() -> i64 {
        ALLOCS.load(Ordering::Relaxed) as i64 - DEALLOCS.load(Ordering::Relaxed) as i64
    }
    /// Print the balance to stderr when enabled; a no-op otherwise. Called from
    /// the driver's main() after roc_main returns.
    pub fn report() {
        if on() {
            eprintln!("[alloc-gauge] allocs={} deallocs={} live={}", ALLOCS.load(Ordering::Relaxed), DEALLOCS.load(Ordering::Relaxed), live());
        }
    }
}

/// Resources (P5): a refcounted opaque host handle. Roc holds a `Box(U64)`
/// whose payload is a raw pointer to a Rust value. Refcounting IS ownership:
/// when Roc drops the last reference its runtime calls `roc_dealloc` with the
/// box's allocation base, and the generated driver's `roc_dealloc` consults
/// this registry first to run the destructor. The glue's own
/// `RocBoxPayloadDecref` only fires on HOST-side decref, so a Roc-side drop
/// needs this hook (B0).
pub mod resource {
    use super::*;
    use core::ffi::c_void;
    use std::collections::HashMap;
    use std::sync::Mutex;

    /// `Box(U64)`: 8-byte payload, align 8, non-refcounted -> header_bytes = 8,
    /// so the allocation base Roc passes to `roc_dealloc` is `data - 8`.
    const HEADER: usize = 8;

    struct Entry {
        raw: *mut c_void,
        dtor: unsafe fn(*mut c_void),
    }
    unsafe impl Send for Entry {}

    static REGISTRY: Mutex<Option<HashMap<usize, Entry>>> = Mutex::new(None);

    unsafe fn drop_boxed<T>(raw: *mut c_void) {
        drop(unsafe { Box::from_raw(raw as *mut T) });
    }

    /// Allocate a resource box holding `value`; Roc receives it as `Box(U64)`.
    pub fn new<T>(value: T) -> RocBox {
        let data = unsafe { allocate_box(8, 8, false, host()) };
        let raw = Box::into_raw(Box::new(value)) as *mut c_void;
        unsafe { *(data as *mut *mut c_void) = raw; }
        let base = data as usize - HEADER;
        if std::env::var_os("HEMATITE_RESOURCE_TRACE").is_some() {
            eprintln!("[resource] new: data={data:p} base={base:#x}");
        }
        let mut g = REGISTRY.lock().unwrap();
        g.get_or_insert_with(HashMap::new)
            .insert(base, Entry { raw, dtor: drop_boxed::<T> });
        data
    }

    /// Borrow the Rust value behind a resource handle.
    ///
    /// # Safety
    /// `b` must be a live resource box created by `new::<T>`.
    pub unsafe fn get<'a, T>(b: RocBox) -> &'a mut T {
        unsafe { &mut *(*(b as *const *mut T)) }
    }

    /// Release one reference to a resource box. **The owned-argument contract:**
    /// a hosted fn that receives a resource OWNS that reference (glue: "hosted
    /// functions receive owned refcounted arguments") and must release it, or
    /// the count never reaches zero and the destructor never runs. On the last
    /// reference this reaches the driver's `roc_dealloc` hook (the linker
    /// symbol), which runs the destructor and frees.
    ///
    /// # Safety
    /// `b` must be a live resource box; the caller must not use it afterward.
    pub unsafe fn release(b: RocBox) {
        use core::sync::atomic::{fence, AtomicIsize, Ordering};
        let data = b as *mut u8;
        let rc = unsafe { data.sub(8) } as *mut AtomicIsize;
        if unsafe { (*rc).load(Ordering::Relaxed) } == 0 {
            return; // static data
        }
        let prev = unsafe { (*rc).fetch_sub(1, Ordering::Release) };
        if prev == 1 {
            fence(Ordering::Acquire);
            unsafe { roc_dealloc((data as usize - HEADER) as *mut c_void, 8) };
        }
    }

    /// Borrow then release in one step — the safe way for a hosted fn to use a
    /// resource argument it owns (the owned-argument contract, B0). Prefer this
    /// over `get` + `release`; forgetting `release` silently leaks the handle.
    ///
    /// # Safety
    /// `b` must be a live resource box created by `new::<T>`; not used after.
    pub unsafe fn with<T, R>(b: RocBox, f: impl FnOnce(&mut T) -> R) -> R {
        let r = f(unsafe { get::<T>(b) });
        unsafe { release(b) };
        r
    }

    /// Called by the generated driver's `roc_dealloc` BEFORE freeing. If `base`
    /// is a registered resource, runs its destructor and unregisters it.
    /// Returns whether it was a resource (for gauges/tests).
    pub fn on_dealloc(base: *mut c_void) -> bool {
        let entry = {
            let mut g = REGISTRY.lock().unwrap();
            g.as_mut().and_then(|m| m.remove(&(base as usize)))
        };
        if std::env::var_os("HEMATITE_RESOURCE_TRACE").is_some() {
            eprintln!("[resource] dealloc: ptr={base:p} {}", if entry.is_some() { "HIT" } else { "miss" });
        }
        match entry {
            Some(e) => {
                unsafe { (e.dtor)(e.raw) };
                true
            }
            None => false,
        }
    }

    /// Number of live (registered, not yet dropped) resources — for tests.
    pub fn live() -> usize {
        REGISTRY.lock().unwrap().as_ref().map_or(0, |m| m.len())
    }
}

/// Zero-copy borrowed slices into host-owned buffers (roc:sqlite-unsound). A
/// `RocStr`/`RocList` whose `bytes` aims at a host buffer (e.g. a live DB cell)
/// while its alloc-ptr aims at a shared, process-global, zero-filled block whose
/// refcount word reads 0 == REFCOUNT_STATIC_DATA: the compiler's own generated
/// incref/decref return without touching a count, so Roc reads the value with
/// native ops but never frees or mutates it. Zero per-cell allocation.
///
/// UNSOUND if a borrow is RETAINED past the host buffer's lifetime (the next
/// step/finalize invalidates a DB cell): the retained value then dangles. The
/// containment discipline (consume-in-place, internal iteration) keeps today's
/// safe uses safe; upstream `clone-on-incref` (an incref of a borrow deep-copies)
/// closes the retain hazard. Hand-written by the composer; the glue never
/// regenerates it.
pub mod borrow {
    use super::{RocListWith, RocStr};

    /// Low bit of `capacity_or_alloc_ptr` marks a seamless slice (mirrors the
    /// generated `ROC_SEAMLESS_SLICE_TAG`). Slice allocations are word-aligned,
    /// so the low bit is always free.
    const ROC_SEAMLESS_SLICE_TAG: usize = 1;

    /// Shared, process-global, zero-filled backing for every borrow. A seamless
    /// slice whose alloc-ptr is `&BORROW_BACKING[1]` reads its refcount at
    /// `&BORROW_BACKING[0]` == 0 == REFCOUNT_STATIC_DATA. Only ever read.
    static BORROW_BACKING: [usize; 2] = [0, 0];

    /// Build a `RocStr` that BORROWS `len` bytes at `ptr` without copying, as a
    /// seamless slice over the shared static (rc==0) backing.
    ///
    /// # Safety
    /// `ptr..ptr+len` must be valid UTF-8 that stays alive and unchanged for as
    /// long as any Roc reference to the returned string can exist; the string
    /// MUST NOT outlive the borrowed bytes.
    pub unsafe fn borrowed_str(ptr: *const u8, len: usize) -> RocStr {
        if len == 0 {
            return RocStr::empty();
        }
        let slot = core::ptr::addr_of!(BORROW_BACKING[1]) as usize;
        RocStr { bytes: ptr as *mut u8, capacity_or_alloc_ptr: slot | ROC_SEAMLESS_SLICE_TAG, length: len }
    }

    /// Build a `List(U8)` that BORROWS `len` bytes at `ptr` — the blob
    /// counterpart to [`borrowed_str`], a seamless slice over the same backing.
    ///
    /// # Safety
    /// Same contract as [`borrowed_str`].
    pub unsafe fn borrowed_bytes(ptr: *const u8, len: usize) -> RocListWith<u8, false> {
        if len == 0 {
            return RocListWith::empty();
        }
        let slot = core::ptr::addr_of!(BORROW_BACKING[1]) as usize;
        RocListWith { elements: ptr as *mut u8, length: len, capacity_or_alloc_ptr: slot | ROC_SEAMLESS_SLICE_TAG }
    }
}
