//! Codegen: emit the composed platform's generated files. Every generated file
//! carries a provenance header (D23). Component sources are copied verbatim,
//! never rewritten (D13). Only these files are hematite's own output:
//!   - platform/main.roc            (spliced requires, hosted union, targets)
//!   - platform/<Module>.roc        (copies of interface + pure-Roc modules)
//!   - Cargo.toml                   (workspace)
//!   - components/<driver>/…        (the driver crate: runtime + main)
//!   - abi/Cargo.toml, abi/src/lib.rs

use crate::manifest::{Driver, World};
use crate::resolve::Resolved;
use std::path::Path;

const GEN: &str = "# GENERATED BY hematite — do not edit. Regenerate with `hematite compose`.";
const GEN_RS: &str = "// GENERATED BY hematite — do not edit. Regenerate with `hematite compose`.";

pub fn emit(
    src: &Path,
    out: &Path,
    world: &World,
    driver: &Driver,
    r: &Resolved,
) -> Result<(), String> {
    let w = |rel: &str, content: String| -> Result<(), String> {
        let p = out.join(rel);
        if let Some(parent) = p.parent() {
            std::fs::create_dir_all(parent).map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
        }
        std::fs::write(&p, content).map_err(|e| format!("write {}: {e}", p.display()))
    };
    let copy = |from: &Path, rel: &str| -> Result<(), String> {
        let p = out.join(rel);
        if let Some(parent) = p.parent() {
            std::fs::create_dir_all(parent).map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
        }
        std::fs::copy(from, &p).map(|_| ()).map_err(|e| format!("copy {}: {e}", p.display()))
    };

    w("platform/main.roc", main_roc(world, driver, r))?;
    w("Cargo.toml", workspace_toml(world, r))?;
    w(&format!("components/{}/Cargo.toml", r.driver), driver_cargo(&r.driver))?;
    w(&format!("components/{}/src/lib.rs", r.driver), driver_lib(driver))?;
    w("abi/Cargo.toml", abi_cargo())?;
    w("abi/src/lib.rs", abi_lib())?;

    // Roc-implemented wiring points: the shim ships the binding module WITH
    // bodies; copy it from the shim component, and skip the interface's
    // declaration-only version (D13, D19).
    let roc_modules: std::collections::BTreeSet<&str> =
        r.roc_impls.iter().map(|(m, _)| m.as_str()).collect();
    for (module, component) in &r.roc_impls {
        let from = src.join("components").join(component).join(format!("{module}.roc"));
        if from.exists() {
            copy(&from, &format!("platform/{module}.roc"))?;
        }
    }
    // Copy interface binding modules into platform/ (host impls + shared types).
    for (iface, module) in &r.interface_modules {
        if roc_modules.contains(module.as_str()) {
            continue; // provided by the shim above
        }
        let from = src.join("interfaces").join(iface).join(format!("{module}.roc"));
        if from.exists() {
            copy(&from, &format!("platform/{module}.roc"))?;
        }
    }
    // Copy pure-Roc components' exported modules into platform/ (D13, verbatim).
    for (name, c) in &world.components {
        if c.kind == "roc" {
            for module in &c.exports {
                let from = src.join("components").join(name).join(format!("{module}.roc"));
                if from.exists() {
                    copy(&from, &format!("platform/{module}.roc"))?;
                }
            }
        }
    }
    Ok(())
}

fn main_roc(world: &World, driver: &Driver, r: &Resolved) -> String {
    let mut s = String::new();
    s.push_str("platform \"\"\n");
    // requires: spliced verbatim from the driver (D18-C).
    s.push_str("\trequires {\n");
    s.push_str(driver.requires.trim_end_matches('\n'));
    s.push('\n');
    s.push_str("\t}\n");
    // exposes: the world's export list (D14).
    s.push_str(&format!("\texposes [{}]\n", world.world.exports.join(", ")));
    s.push_str("\tpackages {}\n");
    s.push_str(&format!("\tprovides {{ \"{}\": {} }}\n", driver.provides_symbol, "main_for_host!"));
    // hosted: the mangled union (D6).
    s.push_str("\thosted {\n");
    for b in &r.hosted {
        s.push_str(&format!("\t\t\"{}\": {}.{},\n", b.symbol, b.module, b.leaf));
    }
    s.push_str("\t}\n");
    // targets: per-target inputs, archives in topological order + app.
    let archives: Vec<String> = r.archive_order.iter().map(|a| format!("\"lib{a}.a\"")).collect();
    let inputs = format!("[{}, app]", archives.join(", "));
    s.push_str("\ttargets: {\n");
    s.push_str("\t\tinputs_dir: \"targets/\",\n");
    s.push_str(&format!("\t\tarm64mac: {{ inputs: {inputs} }},\n"));
    s.push_str(&format!("\t\tx64mac: {{ inputs: {inputs} }},\n"));
    s.push_str("\t}\n\n");
    for m in &r.imports {
        s.push_str(&format!("import {m}\n"));
    }
    s.push('\n');
    // provided adapter: spliced verbatim from the driver.
    s.push_str(driver.provided.trim_matches('\n'));
    s.push('\n');
    s
}

fn workspace_toml(world: &World, r: &Resolved) -> String {
    // members: abi + every host/driver component crate (pure-Roc excluded).
    let mut members = vec!["\"abi\"".to_string()];
    for (name, c) in &world.components {
        if c.kind != "roc" {
            members.push(format!("\"components/{name}\""));
        }
    }
    let _ = r;
    format!(
        "{GEN}\n[workspace]\nresolver = \"2\"\nmembers = [{}]\n\n[profile.release]\npanic = \"unwind\"\n",
        members.join(", ")
    )
}

fn driver_cargo(driver: &str) -> String {
    format!(
        "{GEN}\n[package]\nname = \"{driver}\"\nversion = \"0.0.0\"\nedition = \"2021\"\npublish = false\n\
         [lib]\ncrate-type = [\"staticlib\", \"rlib\"]\n[dependencies]\nhematite-abi = {{ path = \"../../abi\" }}\n"
    )
}

fn driver_lib(_driver: &Driver) -> String {
    // The generated driver: the six runtime symbols (this is the one runtime
    // provider, H0c), and main() wrapping roc_main in catch_unwind with every
    // boundary extern "C-unwind" (H0d). A non-trivial driver (a winit loop)
    // would provide its own driver_main that this generated main() calls; the
    // CLI shape here just calls roc_main directly.
    format!(
        r#"{GEN_RS}
#![allow(dead_code)]
use core::ffi::c_void;
use core::ptr;
use hematite_abi as abi;

#[unsafe(no_mangle)]
pub extern "C" fn roc_alloc(length: usize, alignment: usize) -> *mut c_void {{
    abi::DefaultAllocators::roc_alloc(ptr::null_mut(), length, alignment)
}}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn roc_dealloc(ptr_: *mut c_void, alignment: usize) {{
    abi::DefaultAllocators::roc_dealloc(ptr::null_mut(), ptr_, alignment)
}}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn roc_realloc(ptr_: *mut c_void, new_length: usize, alignment: usize) -> *mut c_void {{
    abi::DefaultAllocators::roc_realloc(ptr::null_mut(), ptr_, new_length, alignment)
}}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn roc_dbg(bytes: *const u8, len: usize) {{
    let m = unsafe {{ core::slice::from_raw_parts(bytes, len) }};
    eprintln!("[roc dbg] {{}}", String::from_utf8_lossy(m));
}}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn roc_expect_failed(bytes: *const u8, len: usize) {{
    let m = unsafe {{ core::slice::from_raw_parts(bytes, len) }};
    eprintln!("[roc expect failed] {{}}", String::from_utf8_lossy(m));
}}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn roc_crashed(bytes: *const u8, len: usize) {{
    let m = unsafe {{ core::slice::from_raw_parts(bytes, len) }};
    eprintln!("[ROC CRASHED] {{}}", String::from_utf8_lossy(m));
    std::process::exit(1);
}}

unsafe extern "C-unwind" {{
    fn roc_main() -> i32;
}}

#[unsafe(no_mangle)]
pub extern "C" fn main(_argc: i32, _argv: *const *const u8) -> i32 {{
    let outcome = std::panic::catch_unwind(|| unsafe {{ roc_main() }});
    match outcome {{
        Ok(code) => code,
        Err(_) => {{
            eprintln!("[hematite] a component panicked; driver caught it at the boundary");
            70
        }}
    }}
}}
"#
    )
}

fn abi_cargo() -> String {
    format!(
        "{GEN}\n[package]\nname = \"hematite-abi\"\nversion = \"0.0.0\"\nedition = \"2021\"\npublish = false\n\
         [lib]\nname = \"hematite_abi\"\ncrate-type = [\"rlib\"]\n"
    )
}

fn abi_lib() -> String {
    format!(
        r#"{GEN_RS}
//! The one ABI crate (D4/D10): `roc glue` output (generated.rs) plus this thin
//! wrapper. Exactly one per composition; every component host depends on it.
#![allow(dead_code, non_camel_case_types, improper_ctypes, improper_ctypes_definitions, unexpected_cfgs)]
mod generated;
pub use generated::*;

use std::sync::OnceLock;

unsafe impl Sync for RocHost {{}}
unsafe impl Send for RocHost {{}}

static HOST: OnceLock<RocHost> = OnceLock::new();

/// The process-wide RocHost (default allocators/handlers over the linker
/// runtime symbols). Cached; used to build owned Roc values.
pub fn host() -> &'static RocHost {{
    HOST.get_or_init(|| make_roc_host(std::ptr::null_mut()))
}}
"#
    )
}
