//! Codegen: emit the composed platform's generated files. Every generated file
//! carries a provenance header (D23). Component sources are copied verbatim,
//! never rewritten (D13). Only these files are hematite's own output:
//!   - platform/main.roc            (spliced requires, hosted union, targets)
//!   - platform/<Module>.roc        (copies of interface + pure-Roc modules)
//!   - Cargo.toml                   (workspace)
//!   - components/<driver>/…        (the driver crate: runtime + main)
//!   - abi/Cargo.toml, abi/src/lib.rs

use crate::manifest::{component_dir, interfaces_dir, module_path, Driver, World};
use crate::resolve::Resolved;
use std::path::Path;

const GEN: &str = "# GENERATED BY hematite — do not edit. Regenerate with `hematite compose`.";
const GEN_RS: &str = "// GENERATED BY hematite — do not edit. Regenerate with `hematite compose`.";

pub fn emit(
    src: &Path,
    out: &Path,
    world: &World,
    driver: &Driver,
    r: &Resolved,
) -> Result<(), String> {
    let w = |rel: &str, content: String| -> Result<(), String> { write_if_changed(&out.join(rel), content.as_bytes()) };
    let copy = |from: &Path, rel: &str| -> Result<(), String> {
        let bytes = std::fs::read(from).map_err(|e| format!("read {}: {e}", from.display()))?;
        write_if_changed(&out.join(rel), &bytes)
    };

    w("platform/main.roc", main_roc(world, driver, r))?;
    // Under a host workspace (cargo_root) the crates already have one; a
    // second, nested workspace claiming them is a cargo error (D-H7-14).
    if world.world.cargo_root.is_none() {
        w("Cargo.toml", workspace_toml(world, r))?;
    }
    // A driver living at its own `path` is an authored crate end to end:
    // hematite writes nothing into it (D-H7-4). Otherwise the crate manifest is
    // generated, and so is the host unless the driver authors it (a reactor
    // driver ships its own src/lib.rs; H7 finding).
    let driver_component = &world.components[&r.driver];
    if driver_component.path.is_none() {
        w(&format!("components/{}/Cargo.toml", r.driver), driver_cargo(&r.driver))?;
        if !driver.authored_host {
            w(&format!("components/{}/src/lib.rs", r.driver), driver_lib(driver))?;
        }
    }
    w("abi/Cargo.toml", abi_cargo())?;
    let shim = crate::services::services_rs(r, driver.services_shim);
    w("abi/src/lib.rs", abi_lib(shim.is_some()))?;
    if let Some(text) = shim {
        w("abi/src/services.rs", text)?;
        w("abi/src/tagged.rs", TAGGED_RS.to_string())?;
    }
    // A service's event/env modules ship beside its command module.
    for (iface, module) in &r.extra_modules {
        let from = interfaces_dir(src, world).join(iface).join(format!("{module}.roc"));
        copy(&from, &format!("platform/{module}.roc"))?;
    }
    // The driver's own contract modules (Cmd/Event/Env/…): copied from its
    // crate with the `## @hematite(...)` blocks filled (D-H7-6).
    let ddir = component_dir(src, &r.driver, driver_component);
    for module in &driver_component.exports {
        let from = module_path(&ddir, module);
        let text = std::fs::read_to_string(&from)
            .map_err(|e| format!("driver `{}` exports `{module}`: read {}: {e}", r.driver, from.display()))?;
        let spliced = crate::splice::splice(&text, &r.services)
            .map_err(|e| format!("{}: {e}", from.display()))?;
        w(&format!("platform/{module}.roc"), spliced)?;
    }

    // Roc-implemented wiring points: the shim ships the binding module WITH
    // bodies; copy it from the shim component, and skip the interface's
    // declaration-only version (D13, D19).
    let roc_modules: std::collections::BTreeSet<&str> =
        r.roc_impls.iter().map(|(m, _)| m.as_str()).collect();
    for (module, component) in &r.roc_impls {
        let from = module_path(&component_dir(src, component, &world.components[component]), module);
        if from.exists() {
            copy(&from, &format!("platform/{module}.roc"))?;
        }
    }
    // Copy interface binding modules into platform/ (host impls + shared types).
    for (iface, module) in &r.interface_modules {
        if roc_modules.contains(module.as_str()) {
            continue; // provided by the shim above
        }
        let from = interfaces_dir(src, world).join(iface).join(format!("{module}.roc"));
        if from.exists() {
            copy(&from, &format!("platform/{module}.roc"))?;
        }
    }
    // Copy pure-Roc components' exported modules into platform/ (D13, verbatim).
    // An export may be renamed on the way in — `"OsPath as Path"` — which is
    // D14's world-rename made real: Roc has no re-export, so the world chooses
    // WHICH implementation is exposed under a name by copying that module's
    // source with its identifier substituted (word-boundary), unchanged
    // otherwise. This is how both path packages ship and a world picks one.
    for (name, c) in &world.components {
        if c.kind == "roc" {
            for entry in &c.exports {
                let (module, as_name) = match entry.split_once(" as ") {
                    Some((m, a)) => (m.trim(), a.trim()),
                    None => (entry.as_str(), entry.as_str()),
                };
                let from = module_path(&component_dir(src, name, c), module);
                if !from.exists() {
                    continue;
                }
                let text = std::fs::read_to_string(&from)
                    .map_err(|e| format!("read {}: {e}", from.display()))?;
                // A pure-Roc component may ship the driver's CONTRACT text —
                // roc-solid's DOM world reuses host-im's modules, marker blocks
                // included (D-H7-30) — so its copies are spliced exactly as a
                // driver's are; a module without markers is copied verbatim.
                let spliced = crate::splice::splice(&text, &r.services)
                    .map_err(|e| format!("{}: {e}", from.display()))?;
                if module == as_name {
                    w(&format!("platform/{module}.roc"), spliced)?;
                } else {
                    w(&format!("platform/{as_name}.roc"), rename_ident(&spliced, module, as_name))?;
                }
            }
        }
    }
    // Per-component Cargo features (HC0/H12): a host component whose manifest
    // sets `features`/`default_features` has its authored Cargo.toml re-emitted
    // with the crate's `[features] default` rewritten to the composed set —
    // everything else verbatim, so the crate's feature *definitions* and deps
    // are untouched. Only the `default` line moves, so whole-workspace
    // `cargo build` builds this member with exactly these features (no CLI
    // flags, no cross-member unification). Components without the fields are
    // left alone (zero churn). The driver's Cargo.toml is generated separately.
    for (name, c) in &world.components {
        if c.kind != "host" {
            continue;
        }
        if c.features.is_empty() && c.default_features.is_none() {
            continue;
        }
        if world.world.cargo_root.is_some() {
            continue; // passed to cargo as --features flags instead (cargo.rs)
        }
        if c.path.is_some() {
            // The rewrite edits the crate's own Cargo.toml; a crate at its own
            // path is shared between worlds, which must not fight over it.
            return Err(format!(
                "component `{name}`: `features`/`default_features` need `[world] cargo_root` with \
                 `path` (the Cargo.toml rewrite would edit a shared crate in place)"
            ));
        }
        let rel = format!("components/{name}/Cargo.toml");
        let from = src.join(&rel);
        let text = std::fs::read_to_string(&from)
            .map_err(|e| format!("read {}: {e}", from.display()))?;
        w(&rel, set_default_features(&text, &c.features))?;
    }
    Ok(())
}

/// Write `content` to `path` only if it differs — an unchanged generated file
/// keeps its mtime, so cargo does not rebuild the abi crate and everything
/// above it (roc-solid's host is 84k lines) on every compose. The same
/// `cmp -s` discipline roc-solid's `im-glue` recipe applied to glue output.
pub fn write_if_changed(path: &Path, content: &[u8]) -> Result<(), String> {
    if std::fs::read(path).is_ok_and(|old| old == content) {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
    }
    std::fs::write(path, content).map_err(|e| format!("write {}: {e}", path.display()))
}

/// Rewrite a Cargo.toml's `[features] default = [...]` array to exactly
/// `features`, preserving every other line (comments, feature definitions,
/// dependencies). Inserts a `[features]` section or a `default` line if absent.
/// Pure in `features`, so composing the same world is idempotent.
fn set_default_features(cargo_toml: &str, features: &[String]) -> String {
    let arr = features.iter().map(|f| format!("\"{f}\"")).collect::<Vec<_>>().join(", ");
    let default_line = format!("default = [{arr}]");
    let mut lines: Vec<String> = cargo_toml.lines().map(str::to_string).collect();
    match lines.iter().position(|l| l.trim() == "[features]") {
        Some(i) => {
            let mut replaced = false;
            let mut j = i + 1;
            while j < lines.len() && !lines[j].trim_start().starts_with('[') {
                if lines[j].split('=').next().map_or(false, |k| k.trim() == "default") {
                    lines[j] = default_line.clone();
                    replaced = true;
                    break;
                }
                j += 1;
            }
            if !replaced {
                lines.insert(i + 1, default_line);
            }
        }
        None => {
            lines.push("[features]".to_string());
            lines.push(default_line);
        }
    }
    let mut out = lines.join("\n");
    if cargo_toml.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Replace whole-identifier occurrences of `from` with `to`.
fn rename_ident(text: &str, from: &str, to: &str) -> String {
    let is_ident = |c: char| c.is_ascii_alphanumeric() || c == '_';
    let mut out = String::with_capacity(text.len());
    let bytes = text.as_bytes();
    let mut i = 0;
    while i < text.len() {
        if text[i..].starts_with(from) {
            let before_ok = i == 0 || !is_ident(bytes[i - 1] as char);
            let after = i + from.len();
            let after_ok = after >= text.len() || !is_ident(bytes[after] as char);
            if before_ok && after_ok {
                out.push_str(to);
                i = after;
                continue;
            }
        }
        let ch = text[i..].chars().next().unwrap();
        out.push(ch);
        i += ch.len_utf8();
    }
    out
}

fn main_roc(world: &World, driver: &Driver, r: &Resolved) -> String {
    let mut s = String::new();
    s.push_str("platform \"\"\n");
    // requires: spliced verbatim from the driver (D18-C).
    s.push_str("\trequires {\n");
    s.push_str(driver.requires.trim_end_matches('\n'));
    s.push('\n');
    s.push_str("\t}\n");
    // exposes: the world's export list (D14).
    s.push_str(&format!("\texposes [{}]\n", world.world.exports.join(", ")));
    if world.packages.is_empty() {
        s.push_str("\tpackages {}\n");
    } else {
        s.push_str("\tpackages {\n");
        for (alias, url) in &world.packages {
            s.push_str(&format!("\t\t{alias}: \"{url}\",\n"));
        }
        s.push_str("\t}\n");
    }
    let entries = driver.provided_entries();
    if entries.len() == 1 {
        s.push_str(&format!("\tprovides {{ \"{}\": {} }}\n", entries[0].0, entries[0].1));
    } else {
        s.push_str("\tprovides {\n");
        for (sym, func) in &entries {
            s.push_str(&format!("\t\t\"{sym}\": {func},\n"));
        }
        s.push_str("\t}\n");
    }
    // hosted: the mangled union (D6).
    s.push_str("\thosted {\n");
    for b in &r.hosted {
        s.push_str(&format!("\t\t\"{}\": {}.{},\n", b.symbol, b.module, b.leaf));
    }
    s.push_str("\t}\n");
    // targets: per-target inputs, archives in topological order + app.
    // cargo emits the staticlib as lib<sanitized>.a (it replaces '-' with '_').
    let archives: Vec<String> = r
        .archive_order
        .iter()
        .map(|a| format!("\"lib{}.a\"", crate::resolve::sanitize(a)))
        .collect();
    let inputs = format!("[{}, app]", archives.join(", "));
    s.push_str("\ttargets: {\n");
    s.push_str("\t\tinputs_dir: \"targets/\",\n");
    s.push_str(&format!("\t\tarm64mac: {{ inputs: {inputs} }},\n"));
    s.push_str(&format!("\t\tx64mac: {{ inputs: {inputs} }},\n"));
    if !driver.wasm_exports.is_empty() {
        // ONE merged host.wasm (D-H7-9 revised): roc links wasm inputs
        // --whole-archive, so per-component inputs collide; `build` merges.
        let exports: Vec<String> = driver.wasm_exports.iter().map(|e| format!("\"{e}\"")).collect();
        s.push_str(&format!(
            "\t\twasm32: {{ inputs: [\"host.wasm\", app], output: Shared, exports: [{}] }},\n",
            exports.join(", ")
        ));
    }
    s.push_str("\t}\n\n");
    for m in &r.imports {
        s.push_str(&format!("import {m}\n"));
    }
    s.push('\n');
    // provided adapter: spliced verbatim from the driver.
    s.push_str(driver.provided.trim_matches('\n'));
    s.push('\n');
    s
}

fn workspace_toml(world: &World, r: &Resolved) -> String {
    // members: abi + every host/driver component crate (pure-Roc excluded).
    let mut members = vec!["\"abi\"".to_string()];
    for (name, c) in &world.components {
        if c.kind != "roc" {
            match &c.path {
                Some(p) => members.push(format!("\"{p}\"")),
                None => members.push(format!("\"components/{name}\"")),
            }
        }
    }
    let _ = r;
    format!(
        "{GEN}\n[workspace]\nresolver = \"2\"\nmembers = [{}]\n\n[profile.release]\npanic = \"unwind\"\n",
        members.join(", ")
    )
}

fn driver_cargo(driver: &str) -> String {
    format!(
        "{GEN}\n[package]\nname = \"{driver}\"\nversion = \"0.0.0\"\nedition = \"2021\"\npublish = false\n\
         [lib]\ncrate-type = [\"staticlib\", \"rlib\"]\n[dependencies]\nhematite-abi = {{ path = \"../../abi\" }}\n"
    )
}

fn driver_lib(_driver: &Driver) -> String {
    // The generated driver: the six runtime symbols (this is the one runtime
    // provider, H0c), and main() wrapping roc_main in catch_unwind with every
    // boundary extern "C-unwind" (H0d). A non-trivial driver (a winit loop)
    // would provide its own driver_main that this generated main() calls; the
    // CLI shape here just calls roc_main directly.
    format!(
        r#"{GEN_RS}
#![allow(dead_code)]
use core::ffi::c_void;
use core::ptr;
use hematite_abi as abi;

#[unsafe(no_mangle)]
pub extern "C" fn roc_alloc(length: usize, alignment: usize) -> *mut c_void {{
    abi::gauge::roc_alloc(ptr::null_mut(), length, alignment)
}}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn roc_dealloc(ptr_: *mut c_void, alignment: usize) {{
    // P5/B0: a resource box's last Roc drop lands here with the allocation
    // base; run its destructor before freeing (the glue has no such hook).
    abi::resource::on_dealloc(ptr_);
    abi::gauge::roc_dealloc(ptr::null_mut(), ptr_, alignment)
}}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn roc_realloc(ptr_: *mut c_void, new_length: usize, alignment: usize) -> *mut c_void {{
    abi::DefaultAllocators::roc_realloc(ptr::null_mut(), ptr_, new_length, alignment)
}}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn roc_dbg(bytes: *const u8, len: usize) {{
    let m = unsafe {{ core::slice::from_raw_parts(bytes, len) }};
    eprintln!("[roc dbg] {{}}", String::from_utf8_lossy(m));
}}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn roc_expect_failed(bytes: *const u8, len: usize) {{
    let m = unsafe {{ core::slice::from_raw_parts(bytes, len) }};
    eprintln!("[roc expect failed] {{}}", String::from_utf8_lossy(m));
}}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn roc_crashed(bytes: *const u8, len: usize) {{
    let m = unsafe {{ core::slice::from_raw_parts(bytes, len) }};
    eprintln!("[ROC CRASHED] {{}}", String::from_utf8_lossy(m));
    std::process::exit(1);
}}

unsafe extern "C-unwind" {{
    fn roc_main() -> i32;
}}

#[unsafe(no_mangle)]
pub extern "C" fn main(_argc: i32, _argv: *const *const u8) -> i32 {{
    let outcome = std::panic::catch_unwind(|| unsafe {{ roc_main() }});
    let code = match outcome {{
        Ok(code) => code,
        Err(_) => {{
            eprintln!("[hematite] a component panicked; driver caught it at the boundary");
            70
        }}
    }};
    abi::gauge::report();
    code
}}
"#
    )
}

fn abi_cargo() -> String {
    format!(
        "{GEN}\n[package]\nname = \"hematite-abi\"\nversion = \"0.0.0\"\nedition = \"2021\"\npublish = false\n\
         [lib]\nname = \"hematite_abi\"\ncrate-type = [\"rlib\"]\n"
    )
}

/// `abi/src/tagged.rs`: build a glue tag-union value from its payload and tag
/// on EITHER pointer width. glue emits the payload as a `union` on 64-bit and
/// as an aligned byte array on 32-bit (wasm32); a struct literal names only
/// one of those, where a write at the value's address is right for both —
/// `#[repr(C)]`, payload first (after a zero-sized alignment marker on
/// 32-bit), every union member at offset 0. The shim's event wrapping and a
/// service's own event building go through this; the pattern is roc-solid's
/// host-dom `tagged::build`, which proved it on wasm32.
const TAGGED_RS: &str = r#"// GENERATED BY hematite — do not edit. Regenerate with `hematite compose`.
//! Build a glue tag-union value from its payload and tag, on either pointer
//! width. See hematite's src/codegen.rs (`TAGGED_RS`).

/// # Safety
/// `T` must be the payload type glue associates with the variant `tag` sets;
/// the wrong one writes a well-formed value of the wrong variant. Size and
/// alignment are asserted rather than documented.
pub unsafe fn build<U, T>(tag: impl FnOnce(&mut U), payload: T) -> U {
    assert!(core::mem::size_of::<T>() <= core::mem::size_of::<U>(), "payload does not fit its tag union");
    assert!(core::mem::align_of::<T>() <= core::mem::align_of::<U>(), "payload over-aligned for its tag union");
    let mut u = core::mem::MaybeUninit::<U>::zeroed();
    // SAFETY: `U` is `#[repr(C)]` with its payload at offset 0 on both widths;
    // zeroed first so padding and any unwritten tail are defined.
    unsafe {
        core::ptr::write(u.as_mut_ptr() as *mut T, payload);
        let mut v = u.assume_init();
        tag(&mut v);
        v
    }
}
"#;

fn abi_lib(with_services: bool) -> String {
    // Byte-identical to the pre-services output when the world has none (the
    // byte-for-byte goldens compare this file).
    let services_mod = if with_services { "pub mod services;\npub mod tagged;\n" } else { "" };
    format!(
        r#"{GEN_RS}
//! The one ABI crate (D4/D10): `roc glue` output (generated.rs) plus this thin
//! wrapper. Exactly one per composition; every component host depends on it.
#![allow(dead_code, non_camel_case_types, improper_ctypes, improper_ctypes_definitions, unexpected_cfgs)]
mod generated;
pub use generated::*;
{services_mod}
use std::sync::OnceLock;

unsafe impl Sync for RocHost {{}}
unsafe impl Send for RocHost {{}}

static HOST: OnceLock<RocHost> = OnceLock::new();

/// The process-wide RocHost (default allocators/handlers over the linker
/// runtime symbols). Cached; used to build owned Roc values.
pub fn host() -> &'static RocHost {{
    HOST.get_or_init(|| {{
        // Route the allocator hooks through the env-gated gauge so host-built
        // Roc values (RocStr::from_str, allocate_box) are counted alongside
        // Roc-initiated allocations (which enter via the driver's roc_alloc
        // symbol). Inert unless HEMATITE_ALLOC_GAUGE is set.
        let mut h = make_roc_host(std::ptr::null_mut());
        h.roc_alloc = gauge::roc_alloc;
        h.roc_dealloc = gauge::roc_dealloc;
        h
    }})
}}

/// Env-gated allocation gauge (test-only): counts Roc allocations vs frees so a
/// verify script can assert drop-balance for refcounted DATA (RocStr/RocList) --
/// the leaks the resource `live()` count cannot see. Every Roc allocation
/// funnels through `DefaultAllocators::roc_alloc`, whether Roc-initiated (the
/// driver's `roc_alloc` symbol) or host-initiated (the RocHost fn pointer), and
/// both are wired here, so the balance is complete. Zero counting cost unless
/// HEMATITE_ALLOC_GAUGE is set (the hooks still delegate, adding only a cached
/// bool check and one relaxed atomic when enabled). `roc_realloc` is a resize,
/// not a net alloc/free, so it is deliberately not counted.
pub mod gauge {{
    use super::*;
    use core::ffi::c_void;
    use core::sync::atomic::{{AtomicU64, Ordering}};
    use std::sync::OnceLock;

    static ENABLED: OnceLock<bool> = OnceLock::new();
    static ALLOCS: AtomicU64 = AtomicU64::new(0);
    static DEALLOCS: AtomicU64 = AtomicU64::new(0);

    #[inline]
    fn on() -> bool {{
        *ENABLED.get_or_init(|| std::env::var_os("HEMATITE_ALLOC_GAUGE").is_some())
    }}

    #[inline]
    pub extern "C" fn roc_alloc(host: *mut RocHost, length: usize, alignment: usize) -> *mut c_void {{
        if on() {{ ALLOCS.fetch_add(1, Ordering::Relaxed); }}
        DefaultAllocators::roc_alloc(host, length, alignment)
    }}
    #[inline]
    pub extern "C" fn roc_dealloc(host: *mut RocHost, ptr: *mut c_void, alignment: usize) {{
        if on() {{ DEALLOCS.fetch_add(1, Ordering::Relaxed); }}
        DefaultAllocators::roc_dealloc(host, ptr, alignment)
    }}

    /// Roc allocations still live (allocs - deallocs); 0 at a clean exit.
    pub fn live() -> i64 {{
        ALLOCS.load(Ordering::Relaxed) as i64 - DEALLOCS.load(Ordering::Relaxed) as i64
    }}
    /// Print the balance to stderr when enabled; a no-op otherwise. Called from
    /// the driver's main() after roc_main returns.
    pub fn report() {{
        if on() {{
            eprintln!("[alloc-gauge] allocs={{}} deallocs={{}} live={{}}", ALLOCS.load(Ordering::Relaxed), DEALLOCS.load(Ordering::Relaxed), live());
        }}
    }}
}}

/// Resources (P5): a refcounted opaque host handle. Roc holds a `Box(U64)`
/// whose payload is a raw pointer to a Rust value. Refcounting IS ownership:
/// when Roc drops the last reference its runtime calls `roc_dealloc` with the
/// box's allocation base, and the generated driver's `roc_dealloc` consults
/// this registry first to run the destructor. The glue's own
/// `RocBoxPayloadDecref` only fires on HOST-side decref, so a Roc-side drop
/// needs this hook (B0).
pub mod resource {{
    use super::*;
    use core::ffi::c_void;
    use std::collections::HashMap;
    use std::sync::Mutex;

    /// `Box(U64)`: 8-byte payload, align 8, non-refcounted -> header_bytes = 8,
    /// so the allocation base Roc passes to `roc_dealloc` is `data - 8`.
    const HEADER: usize = 8;

    struct Entry {{
        raw: *mut c_void,
        dtor: unsafe fn(*mut c_void),
    }}
    unsafe impl Send for Entry {{}}

    static REGISTRY: Mutex<Option<HashMap<usize, Entry>>> = Mutex::new(None);

    unsafe fn drop_boxed<T>(raw: *mut c_void) {{
        drop(unsafe {{ Box::from_raw(raw as *mut T) }});
    }}

    /// Allocate a resource box holding `value`; Roc receives it as `Box(U64)`.
    pub fn new<T>(value: T) -> RocBox {{
        let data = unsafe {{ allocate_box(8, 8, false, host()) }};
        let raw = Box::into_raw(Box::new(value)) as *mut c_void;
        unsafe {{ *(data as *mut *mut c_void) = raw; }}
        let base = data as usize - HEADER;
        if std::env::var_os("HEMATITE_RESOURCE_TRACE").is_some() {{
            eprintln!("[resource] new: data={{data:p}} base={{base:#x}}");
        }}
        let mut g = REGISTRY.lock().unwrap();
        g.get_or_insert_with(HashMap::new)
            .insert(base, Entry {{ raw, dtor: drop_boxed::<T> }});
        data
    }}

    /// Borrow the Rust value behind a resource handle.
    ///
    /// # Safety
    /// `b` must be a live resource box created by `new::<T>`.
    pub unsafe fn get<'a, T>(b: RocBox) -> &'a mut T {{
        unsafe {{ &mut *(*(b as *const *mut T)) }}
    }}

    /// Release one reference to a resource box. **The owned-argument contract:**
    /// a hosted fn that receives a resource OWNS that reference (glue: "hosted
    /// functions receive owned refcounted arguments") and must release it, or
    /// the count never reaches zero and the destructor never runs. On the last
    /// reference this reaches the driver's `roc_dealloc` hook (the linker
    /// symbol), which runs the destructor and frees.
    ///
    /// # Safety
    /// `b` must be a live resource box; the caller must not use it afterward.
    pub unsafe fn release(b: RocBox) {{
        use core::sync::atomic::{{fence, AtomicIsize, Ordering}};
        let data = b as *mut u8;
        let rc = unsafe {{ data.sub(8) }} as *mut AtomicIsize;
        if unsafe {{ (*rc).load(Ordering::Relaxed) }} == 0 {{
            return; // static data
        }}
        let prev = unsafe {{ (*rc).fetch_sub(1, Ordering::Release) }};
        if prev == 1 {{
            fence(Ordering::Acquire);
            unsafe {{ roc_dealloc((data as usize - HEADER) as *mut c_void, 8) }};
        }}
    }}

    /// Borrow then release in one step — the safe way for a hosted fn to use a
    /// resource argument it owns (the owned-argument contract, B0). Prefer this
    /// over `get` + `release`; forgetting `release` silently leaks the handle.
    ///
    /// # Safety
    /// `b` must be a live resource box created by `new::<T>`; not used after.
    pub unsafe fn with<T, R>(b: RocBox, f: impl FnOnce(&mut T) -> R) -> R {{
        let r = f(unsafe {{ get::<T>(b) }});
        unsafe {{ release(b) }};
        r
    }}

    /// Called by the generated driver's `roc_dealloc` BEFORE freeing. If `base`
    /// is a registered resource, runs its destructor and unregisters it.
    /// Returns whether it was a resource (for gauges/tests).
    pub fn on_dealloc(base: *mut c_void) -> bool {{
        let entry = {{
            let mut g = REGISTRY.lock().unwrap();
            g.as_mut().and_then(|m| m.remove(&(base as usize)))
        }};
        if std::env::var_os("HEMATITE_RESOURCE_TRACE").is_some() {{
            eprintln!("[resource] dealloc: ptr={{base:p}} {{}}", if entry.is_some() {{ "HIT" }} else {{ "miss" }});
        }}
        match entry {{
            Some(e) => {{
                unsafe {{ (e.dtor)(e.raw) }};
                true
            }}
            None => false,
        }}
    }}

    /// Number of live (registered, not yet dropped) resources — for tests.
    pub fn live() -> usize {{
        REGISTRY.lock().unwrap().as_ref().map_or(0, |m| m.len())
    }}
}}

/// Zero-copy borrowed slices into host-owned buffers (roc:sqlite-unsound). A
/// `RocStr`/`RocList` whose `bytes` aims at a host buffer (e.g. a live DB cell)
/// while its alloc-ptr aims at a shared, process-global, zero-filled block whose
/// refcount word reads 0 == REFCOUNT_STATIC_DATA: the compiler's own generated
/// incref/decref return without touching a count, so Roc reads the value with
/// native ops but never frees or mutates it. Zero per-cell allocation.
///
/// UNSOUND if a borrow is RETAINED past the host buffer's lifetime (the next
/// step/finalize invalidates a DB cell): the retained value then dangles. The
/// containment discipline (consume-in-place, internal iteration) keeps today's
/// safe uses safe; upstream `clone-on-incref` (an incref of a borrow deep-copies)
/// closes the retain hazard. Hand-written by the composer; the glue never
/// regenerates it.
pub mod borrow {{
    use super::{{RocListWith, RocStr}};

    /// Low bit of `capacity_or_alloc_ptr` marks a seamless slice (mirrors the
    /// generated `ROC_SEAMLESS_SLICE_TAG`). Slice allocations are word-aligned,
    /// so the low bit is always free.
    const ROC_SEAMLESS_SLICE_TAG: usize = 1;

    /// Shared, process-global, zero-filled backing for every borrow. A seamless
    /// slice whose alloc-ptr is `&BORROW_BACKING[1]` reads its refcount at
    /// `&BORROW_BACKING[0]` == 0 == REFCOUNT_STATIC_DATA. Only ever read.
    static BORROW_BACKING: [usize; 2] = [0, 0];

    /// Build a `RocStr` that BORROWS `len` bytes at `ptr` without copying, as a
    /// seamless slice over the shared static (rc==0) backing.
    ///
    /// # Safety
    /// `ptr..ptr+len` must be valid UTF-8 that stays alive and unchanged for as
    /// long as any Roc reference to the returned string can exist; the string
    /// MUST NOT outlive the borrowed bytes.
    pub unsafe fn borrowed_str(ptr: *const u8, len: usize) -> RocStr {{
        if len == 0 {{
            return RocStr::empty();
        }}
        let slot = core::ptr::addr_of!(BORROW_BACKING[1]) as usize;
        RocStr {{ bytes: ptr as *mut u8, capacity_or_alloc_ptr: slot | ROC_SEAMLESS_SLICE_TAG, length: len }}
    }}

    /// Build a `List(U8)` that BORROWS `len` bytes at `ptr` — the blob
    /// counterpart to [`borrowed_str`], a seamless slice over the same backing.
    ///
    /// # Safety
    /// Same contract as [`borrowed_str`].
    pub unsafe fn borrowed_bytes(ptr: *const u8, len: usize) -> RocListWith<u8, false> {{
        if len == 0 {{
            return RocListWith::empty();
        }}
        let slot = core::ptr::addr_of!(BORROW_BACKING[1]) as usize;
        RocListWith {{ elements: ptr as *mut u8, length: len, capacity_or_alloc_ptr: slot | ROC_SEAMLESS_SLICE_TAG }}
    }}
}}
"#
    )
}
