//! Codegen: emit the composed platform's generated files. Every generated file
//! carries a provenance header (D23). Component sources are copied verbatim,
//! never rewritten (D13). Only these files are hematite's own output:
//!   - platform/main.roc            (spliced requires, hosted union, targets)
//!   - platform/<Module>.roc        (copies of interface + pure-Roc modules)
//!   - Cargo.toml                   (workspace)
//!   - components/<driver>/…        (the driver crate: runtime + main)
//!   - abi/Cargo.toml, abi/src/lib.rs

use crate::manifest::{Driver, World};
use crate::resolve::Resolved;
use std::path::Path;

const GEN: &str = "# GENERATED BY hematite — do not edit. Regenerate with `hematite compose`.";
const GEN_RS: &str = "// GENERATED BY hematite — do not edit. Regenerate with `hematite compose`.";

pub fn emit(
    src: &Path,
    out: &Path,
    world: &World,
    driver: &Driver,
    r: &Resolved,
) -> Result<(), String> {
    let w = |rel: &str, content: String| -> Result<(), String> {
        let p = out.join(rel);
        if let Some(parent) = p.parent() {
            std::fs::create_dir_all(parent).map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
        }
        std::fs::write(&p, content).map_err(|e| format!("write {}: {e}", p.display()))
    };
    let copy = |from: &Path, rel: &str| -> Result<(), String> {
        let p = out.join(rel);
        if let Some(parent) = p.parent() {
            std::fs::create_dir_all(parent).map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
        }
        std::fs::copy(from, &p).map(|_| ()).map_err(|e| format!("copy {}: {e}", p.display()))
    };

    w("platform/main.roc", main_roc(world, driver, r))?;
    w("Cargo.toml", workspace_toml(world, r))?;
    w(&format!("components/{}/Cargo.toml", r.driver), driver_cargo(&r.driver))?;
    // A CLI driver's host is generated; a reactor driver (authored_host) ships
    // its own src/lib.rs and hematite must not clobber it (H7 finding).
    if !driver.authored_host {
        w(&format!("components/{}/src/lib.rs", r.driver), driver_lib(driver))?;
    }
    w("abi/Cargo.toml", abi_cargo())?;
    w("abi/src/lib.rs", abi_lib())?;

    // Roc-implemented wiring points: the shim ships the binding module WITH
    // bodies; copy it from the shim component, and skip the interface's
    // declaration-only version (D13, D19).
    let roc_modules: std::collections::BTreeSet<&str> =
        r.roc_impls.iter().map(|(m, _)| m.as_str()).collect();
    for (module, component) in &r.roc_impls {
        let from = src.join("components").join(component).join(format!("{module}.roc"));
        if from.exists() {
            copy(&from, &format!("platform/{module}.roc"))?;
        }
    }
    // Copy interface binding modules into platform/ (host impls + shared types).
    for (iface, module) in &r.interface_modules {
        if roc_modules.contains(module.as_str()) {
            continue; // provided by the shim above
        }
        let from = src.join("interfaces").join(iface).join(format!("{module}.roc"));
        if from.exists() {
            copy(&from, &format!("platform/{module}.roc"))?;
        }
    }
    // Copy pure-Roc components' exported modules into platform/ (D13, verbatim).
    // An export may be renamed on the way in — `"OsPath as Path"` — which is
    // D14's world-rename made real: Roc has no re-export, so the world chooses
    // WHICH implementation is exposed under a name by copying that module's
    // source with its identifier substituted (word-boundary), unchanged
    // otherwise. This is how both path packages ship and a world picks one.
    for (name, c) in &world.components {
        if c.kind == "roc" {
            for entry in &c.exports {
                let (module, as_name) = match entry.split_once(" as ") {
                    Some((m, a)) => (m.trim(), a.trim()),
                    None => (entry.as_str(), entry.as_str()),
                };
                let from = src.join("components").join(name).join(format!("{module}.roc"));
                if !from.exists() {
                    continue;
                }
                if module == as_name {
                    copy(&from, &format!("platform/{module}.roc"))?;
                } else {
                    let text = std::fs::read_to_string(&from)
                        .map_err(|e| format!("read {}: {e}", from.display()))?;
                    let renamed = rename_ident(&text, module, as_name);
                    w(&format!("platform/{as_name}.roc"), renamed)?;
                }
            }
        }
    }
    Ok(())
}

/// Replace whole-identifier occurrences of `from` with `to`.
fn rename_ident(text: &str, from: &str, to: &str) -> String {
    let is_ident = |c: char| c.is_ascii_alphanumeric() || c == '_';
    let mut out = String::with_capacity(text.len());
    let bytes = text.as_bytes();
    let mut i = 0;
    while i < text.len() {
        if text[i..].starts_with(from) {
            let before_ok = i == 0 || !is_ident(bytes[i - 1] as char);
            let after = i + from.len();
            let after_ok = after >= text.len() || !is_ident(bytes[after] as char);
            if before_ok && after_ok {
                out.push_str(to);
                i = after;
                continue;
            }
        }
        let ch = text[i..].chars().next().unwrap();
        out.push(ch);
        i += ch.len_utf8();
    }
    out
}

fn main_roc(world: &World, driver: &Driver, r: &Resolved) -> String {
    let mut s = String::new();
    s.push_str("platform \"\"\n");
    // requires: spliced verbatim from the driver (D18-C).
    s.push_str("\trequires {\n");
    s.push_str(driver.requires.trim_end_matches('\n'));
    s.push('\n');
    s.push_str("\t}\n");
    // exposes: the world's export list (D14).
    s.push_str(&format!("\texposes [{}]\n", world.world.exports.join(", ")));
    s.push_str("\tpackages {}\n");
    let entries = driver.provided_entries();
    if entries.len() == 1 {
        s.push_str(&format!("\tprovides {{ \"{}\": {} }}\n", entries[0].0, entries[0].1));
    } else {
        s.push_str("\tprovides {\n");
        for (sym, func) in &entries {
            s.push_str(&format!("\t\t\"{sym}\": {func},\n"));
        }
        s.push_str("\t}\n");
    }
    // hosted: the mangled union (D6).
    s.push_str("\thosted {\n");
    for b in &r.hosted {
        s.push_str(&format!("\t\t\"{}\": {}.{},\n", b.symbol, b.module, b.leaf));
    }
    s.push_str("\t}\n");
    // targets: per-target inputs, archives in topological order + app.
    // cargo emits the staticlib as lib<sanitized>.a (it replaces '-' with '_').
    let archives: Vec<String> = r
        .archive_order
        .iter()
        .map(|a| format!("\"lib{}.a\"", crate::resolve::sanitize(a)))
        .collect();
    let inputs = format!("[{}, app]", archives.join(", "));
    s.push_str("\ttargets: {\n");
    s.push_str("\t\tinputs_dir: \"targets/\",\n");
    s.push_str(&format!("\t\tarm64mac: {{ inputs: {inputs} }},\n"));
    s.push_str(&format!("\t\tx64mac: {{ inputs: {inputs} }},\n"));
    s.push_str("\t}\n\n");
    for m in &r.imports {
        s.push_str(&format!("import {m}\n"));
    }
    s.push('\n');
    // provided adapter: spliced verbatim from the driver.
    s.push_str(driver.provided.trim_matches('\n'));
    s.push('\n');
    s
}

fn workspace_toml(world: &World, r: &Resolved) -> String {
    // members: abi + every host/driver component crate (pure-Roc excluded).
    let mut members = vec!["\"abi\"".to_string()];
    for (name, c) in &world.components {
        if c.kind != "roc" {
            members.push(format!("\"components/{name}\""));
        }
    }
    let _ = r;
    format!(
        "{GEN}\n[workspace]\nresolver = \"2\"\nmembers = [{}]\n\n[profile.release]\npanic = \"unwind\"\n",
        members.join(", ")
    )
}

fn driver_cargo(driver: &str) -> String {
    format!(
        "{GEN}\n[package]\nname = \"{driver}\"\nversion = \"0.0.0\"\nedition = \"2021\"\npublish = false\n\
         [lib]\ncrate-type = [\"staticlib\", \"rlib\"]\n[dependencies]\nhematite-abi = {{ path = \"../../abi\" }}\n"
    )
}

fn driver_lib(_driver: &Driver) -> String {
    // The generated driver: the six runtime symbols (this is the one runtime
    // provider, H0c), and main() wrapping roc_main in catch_unwind with every
    // boundary extern "C-unwind" (H0d). A non-trivial driver (a winit loop)
    // would provide its own driver_main that this generated main() calls; the
    // CLI shape here just calls roc_main directly.
    format!(
        r#"{GEN_RS}
#![allow(dead_code)]
use core::ffi::c_void;
use core::ptr;
use hematite_abi as abi;

#[unsafe(no_mangle)]
pub extern "C" fn roc_alloc(length: usize, alignment: usize) -> *mut c_void {{
    abi::DefaultAllocators::roc_alloc(ptr::null_mut(), length, alignment)
}}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn roc_dealloc(ptr_: *mut c_void, alignment: usize) {{
    // P5/B0: a resource box's last Roc drop lands here with the allocation
    // base; run its destructor before freeing (the glue has no such hook).
    abi::resource::on_dealloc(ptr_);
    abi::DefaultAllocators::roc_dealloc(ptr::null_mut(), ptr_, alignment)
}}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn roc_realloc(ptr_: *mut c_void, new_length: usize, alignment: usize) -> *mut c_void {{
    abi::DefaultAllocators::roc_realloc(ptr::null_mut(), ptr_, new_length, alignment)
}}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn roc_dbg(bytes: *const u8, len: usize) {{
    let m = unsafe {{ core::slice::from_raw_parts(bytes, len) }};
    eprintln!("[roc dbg] {{}}", String::from_utf8_lossy(m));
}}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn roc_expect_failed(bytes: *const u8, len: usize) {{
    let m = unsafe {{ core::slice::from_raw_parts(bytes, len) }};
    eprintln!("[roc expect failed] {{}}", String::from_utf8_lossy(m));
}}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn roc_crashed(bytes: *const u8, len: usize) {{
    let m = unsafe {{ core::slice::from_raw_parts(bytes, len) }};
    eprintln!("[ROC CRASHED] {{}}", String::from_utf8_lossy(m));
    std::process::exit(1);
}}

unsafe extern "C-unwind" {{
    fn roc_main() -> i32;
}}

#[unsafe(no_mangle)]
pub extern "C" fn main(_argc: i32, _argv: *const *const u8) -> i32 {{
    let outcome = std::panic::catch_unwind(|| unsafe {{ roc_main() }});
    match outcome {{
        Ok(code) => code,
        Err(_) => {{
            eprintln!("[hematite] a component panicked; driver caught it at the boundary");
            70
        }}
    }}
}}
"#
    )
}

fn abi_cargo() -> String {
    format!(
        "{GEN}\n[package]\nname = \"hematite-abi\"\nversion = \"0.0.0\"\nedition = \"2021\"\npublish = false\n\
         [lib]\nname = \"hematite_abi\"\ncrate-type = [\"rlib\"]\n"
    )
}

fn abi_lib() -> String {
    format!(
        r#"{GEN_RS}
//! The one ABI crate (D4/D10): `roc glue` output (generated.rs) plus this thin
//! wrapper. Exactly one per composition; every component host depends on it.
#![allow(dead_code, non_camel_case_types, improper_ctypes, improper_ctypes_definitions, unexpected_cfgs)]
mod generated;
pub use generated::*;

use std::sync::OnceLock;

unsafe impl Sync for RocHost {{}}
unsafe impl Send for RocHost {{}}

static HOST: OnceLock<RocHost> = OnceLock::new();

/// The process-wide RocHost (default allocators/handlers over the linker
/// runtime symbols). Cached; used to build owned Roc values.
pub fn host() -> &'static RocHost {{
    HOST.get_or_init(|| make_roc_host(std::ptr::null_mut()))
}}

/// Resources (P5): a refcounted opaque host handle. Roc holds a `Box(U64)`
/// whose payload is a raw pointer to a Rust value. Refcounting IS ownership:
/// when Roc drops the last reference its runtime calls `roc_dealloc` with the
/// box's allocation base, and the generated driver's `roc_dealloc` consults
/// this registry first to run the destructor. The glue's own
/// `RocBoxPayloadDecref` only fires on HOST-side decref, so a Roc-side drop
/// needs this hook (B0).
pub mod resource {{
    use super::*;
    use core::ffi::c_void;
    use std::collections::HashMap;
    use std::sync::Mutex;

    /// `Box(U64)`: 8-byte payload, align 8, non-refcounted -> header_bytes = 8,
    /// so the allocation base Roc passes to `roc_dealloc` is `data - 8`.
    const HEADER: usize = 8;

    struct Entry {{
        raw: *mut c_void,
        dtor: unsafe fn(*mut c_void),
    }}
    unsafe impl Send for Entry {{}}

    static REGISTRY: Mutex<Option<HashMap<usize, Entry>>> = Mutex::new(None);

    unsafe fn drop_boxed<T>(raw: *mut c_void) {{
        drop(unsafe {{ Box::from_raw(raw as *mut T) }});
    }}

    /// Allocate a resource box holding `value`; Roc receives it as `Box(U64)`.
    pub fn new<T>(value: T) -> RocBox {{
        let data = unsafe {{ allocate_box(8, 8, false, host()) }};
        let raw = Box::into_raw(Box::new(value)) as *mut c_void;
        unsafe {{ *(data as *mut *mut c_void) = raw; }}
        let base = data as usize - HEADER;
        if std::env::var_os("HEMATITE_RESOURCE_TRACE").is_some() {{
            eprintln!("[resource] new: data={{data:p}} base={{base:#x}}");
        }}
        let mut g = REGISTRY.lock().unwrap();
        g.get_or_insert_with(HashMap::new)
            .insert(base, Entry {{ raw, dtor: drop_boxed::<T> }});
        data
    }}

    /// Borrow the Rust value behind a resource handle.
    ///
    /// # Safety
    /// `b` must be a live resource box created by `new::<T>`.
    pub unsafe fn get<'a, T>(b: RocBox) -> &'a mut T {{
        unsafe {{ &mut *(*(b as *const *mut T)) }}
    }}

    /// Release one reference to a resource box. **The owned-argument contract:**
    /// a hosted fn that receives a resource OWNS that reference (glue: "hosted
    /// functions receive owned refcounted arguments") and must release it, or
    /// the count never reaches zero and the destructor never runs. On the last
    /// reference this reaches the driver's `roc_dealloc` hook (the linker
    /// symbol), which runs the destructor and frees.
    ///
    /// # Safety
    /// `b` must be a live resource box; the caller must not use it afterward.
    pub unsafe fn release(b: RocBox) {{
        use core::sync::atomic::{{fence, AtomicIsize, Ordering}};
        let data = b as *mut u8;
        let rc = unsafe {{ data.sub(8) }} as *mut AtomicIsize;
        if unsafe {{ (*rc).load(Ordering::Relaxed) }} == 0 {{
            return; // static data
        }}
        let prev = unsafe {{ (*rc).fetch_sub(1, Ordering::Release) }};
        if prev == 1 {{
            fence(Ordering::Acquire);
            unsafe {{ roc_dealloc((data as usize - HEADER) as *mut c_void, 8) }};
        }}
    }}

    /// Borrow then release in one step — the safe way for a hosted fn to use a
    /// resource argument it owns (the owned-argument contract, B0). Prefer this
    /// over `get` + `release`; forgetting `release` silently leaks the handle.
    ///
    /// # Safety
    /// `b` must be a live resource box created by `new::<T>`; not used after.
    pub unsafe fn with<T, R>(b: RocBox, f: impl FnOnce(&mut T) -> R) -> R {{
        let r = f(unsafe {{ get::<T>(b) }});
        unsafe {{ release(b) }};
        r
    }}

    /// Called by the generated driver's `roc_dealloc` BEFORE freeing. If `base`
    /// is a registered resource, runs its destructor and unregisters it.
    /// Returns whether it was a resource (for gauges/tests).
    pub fn on_dealloc(base: *mut c_void) -> bool {{
        let entry = {{
            let mut g = REGISTRY.lock().unwrap();
            g.as_mut().and_then(|m| m.remove(&(base as usize)))
        }};
        if std::env::var_os("HEMATITE_RESOURCE_TRACE").is_some() {{
            eprintln!("[resource] dealloc: ptr={{base:p}} {{}}", if entry.is_some() {{ "HIT" }} else {{ "miss" }});
        }}
        match entry {{
            Some(e) => {{
                unsafe {{ (e.dtor)(e.raw) }};
                true
            }}
            None => false,
        }}
    }}

    /// Number of live (registered, not yet dropped) resources — for tests.
    pub fn live() -> usize {{
        REGISTRY.lock().unwrap().as_ref().map_or(0, |m| m.len())
    }}
}}
"#
    )
}
