//! `trantor new-interface` (plan U1 P5): an interface, its host component, and
//! the wiring, ready for `interface-stub`.
use std::path::Path;

use crate::scaffold::write_new;

/// `trantor new-interface <name>` — the scaffolding `interface-stub` fills in.
pub fn new_interface(dir: &Path, world_file: &str, name: &str) -> Result<(), String> {
    let module: String = {
        let mut c = name.split(['-', '_']).filter(|s| !s.is_empty()).map(|s| {
            let mut ch = s.chars();
            ch.next().map(|f| f.to_uppercase().collect::<String>() + ch.as_str()).unwrap_or_default()
        });
        c.next().unwrap_or_default() + &c.collect::<String>()
    };
    if module.is_empty() {
        return Err(format!("new-interface: {name:?} is not a usable interface name"));
    }
    let comp = format!("{name}-host");
    let idir = dir.join("interfaces").join(name);
    write_new(
        &idir.join("interface.toml"),
        &format!(
            "module = {module:?}\n\n# One entry per hosted function. `leaf` is what Roc calls;\n\
             # `symbol_stem` becomes trantor__{}__<stem> in Rust.\n\
             [[hosted]]\nleaf = \"do_it!\"\nsymbol_stem = \"do_it\"\n",
            crate::resolve::sanitize(&comp)
        ),
    )?;
    write_new(
        &idir.join(format!("{module}.roc")),
        &format!("{module} :: [].{{\n\tdo_it! : Str => Str\n}}\n"),
    )?;
    let cdir = dir.join("components").join(&comp);
    write_new(
        &cdir.join("Cargo.toml"),
        &format!(
            "[package]\nname = {comp:?}\nversion = \"0.0.0\"\nedition = \"2021\"\npublish = false\n\
             [lib]\ncrate-type = [\"staticlib\", \"rlib\"]\n\n[dependencies]\n\
             # Generated by trantor; the workspace `[patch.crates-io]` resolves it.\n\
             trantor-abi = \"0.0.0\"\n"
        ),
    )?;
    // A [lib] with no source is a manifest cargo cannot even parse, so `cargo
    // add` and `cargo metadata` fail here before the user has done anything
    // wrong. `interface-stub` replaces this file wholesale — comments and
    // nothing else is exactly what it recognises as safe to overwrite, so
    // keep it that way (`stub::is_scaffolding`).
    write_new(
        &cdir.join("src/lib.rs"),
        &format!(
            "//! Host implementation of interface `{name}`.\n             //! Run `trantor interface-stub {name}` to replace this with the\n             //! signatures generated from interfaces/{name}/{module}.roc.\n"
        ),
    )?;

    // Wire it up, preserving the manifest's own formatting and comments.
    let wp = dir.join(world_file);
    let text = std::fs::read_to_string(&wp).map_err(|e| format!("read {}: {e}", wp.display()))?;
    let mut doc = text
        .parse::<toml_edit::DocumentMut>()
        .map_err(|e| format!("parse {}: {e}", wp.display()))?;
    for key in ["interfaces", "components", "wiring"] {
        if let Some(t) = doc[key].or_insert(toml_edit::table()).as_table_mut() {
            t.set_implicit(true);
        }
    }
    doc["interfaces"][name] = toml_edit::table();
    let mut c = toml_edit::table();
    c["kind"] = toml_edit::value("host");
    c["lang"] = toml_edit::value("rust");
    let mut ex = toml_edit::Array::new();
    ex.push(name);
    c["exports"] = toml_edit::value(ex);
    doc["components"][&comp] = c;
    doc["wiring"][name] = toml_edit::value(comp.clone());
    // The app must be able to import it.
    let exports = doc["world"]["exports"].or_insert(toml_edit::value(toml_edit::Array::new()));
    if let Some(a) = exports.as_array_mut() {
        if !a.iter().any(|v| v.as_str() == Some(module.as_str())) {
            a.push(module.as_str());
        }
    }
    std::fs::write(&wp, doc.to_string()).map_err(|e| format!("write {}: {e}", wp.display()))?;

    // And into the user's own cargo workspace, so the editor sees the crate.
    let cargo = dir.join("Cargo.toml");
    if let Ok(t) = std::fs::read_to_string(&cargo) {
        if let Ok(mut d) = t.parse::<toml_edit::DocumentMut>() {
            if let Some(m) = d["workspace"]["members"].as_array_mut() {
                let entry = format!("components/{comp}");
                if !m.iter().any(|v| v.as_str() == Some(entry.as_str())) {
                    m.push(entry.as_str());
                    let _ = std::fs::write(&cargo, d.to_string());
                }
            }
        }
    }

    eprintln!(
        "trantor: added interface `{name}` (module {module}) and component `{comp}`.\n\
         trantor: edit interfaces/{name}/{module}.roc, then `trantor interface-stub {name}` \
         for the Rust signatures."
    );
    Ok(())
}
