//! Getting a dependency's source onto disk, and recording exactly which one
//! (D-U1-3): `trantor add <org>/<repo>` resolves the newest semver tag, or the
//! default branch's HEAD when a repo has no tags, and pins the commit.
//!
//! Everything here is `git` and plain HTTPS. `git ls-remote` lists refs,
//! `git fetch` takes a sha, and none of it touches api.github.com — so `add`
//! needs no token, hits no unauthenticated rate limit, and works anywhere git
//! works. Reaching for the REST API to list tags would buy nothing and cost
//! that property, which is why a test asserts no code path builds that host.

use crate::manifest::DepSource;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;

pub const LOCK_FILE: &str = "trantor.lock";

/// `$TRANTOR_HOME`, else `~/.trantor`. The env var is what lets a test run
/// against a cache of its own instead of the developer's.
pub fn home() -> Result<PathBuf, String> {
    if let Ok(h) = std::env::var("TRANTOR_HOME") {
        return Ok(PathBuf::from(h));
    }
    std::env::var("HOME")
        .map(|h| PathBuf::from(h).join(".trantor"))
        .map_err(|_| "neither $TRANTOR_HOME nor $HOME is set, so there is nowhere to cache dependencies".to_string())
}

/// Keyed by package identity AND commit, so two packages never share a
/// directory and two commits of one package coexist.
pub fn cache_dir(slug: &str, commit: &str) -> Result<PathBuf, String> {
    let (org, repo) = slug
        .split_once('/')
        .ok_or_else(|| format!("bad repo slug {slug:?}"))?;
    Ok(home()?.join("cache/git").join(org).join(repo).join(commit))
}

#[derive(Debug, Clone, PartialEq)]
pub struct Entry {
    pub name: String,
    pub github: String,
    /// Exactly one of these; a repo with no semver tags is pinned by branch.
    pub tag: Option<String>,
    pub branch: Option<String>,
    pub commit: String,
}

#[derive(Debug, Default)]
pub struct Lock {
    pub packages: Vec<Entry>,
}

impl Lock {
    pub fn get(&self, name: &str) -> Option<&Entry> {
        self.packages.iter().find(|e| e.name == name)
    }

    pub fn load(dir: &Path) -> Result<Lock, String> {
        let p = dir.join(LOCK_FILE);
        let Ok(text) = std::fs::read_to_string(&p) else {
            return Ok(Lock::default());
        };
        let doc: toml::Value =
            toml::from_str(&text).map_err(|e| format!("parse {}: {e}", p.display()))?;
        let mut packages = Vec::new();
        for v in doc.get("package").and_then(|p| p.as_array()).into_iter().flatten() {
            let s = |k: &str| v.get(k).and_then(|x| x.as_str()).map(str::to_string);
            let (Some(name), Some(github), Some(commit)) = (s("name"), s("github"), s("commit"))
            else {
                return Err(format!(
                    "{}: a [[package]] entry is missing name, github or commit. Delete the file \
                     and re-run `trantor add` rather than hand-repairing it.",
                    p.display()
                ));
            };
            packages.push(Entry { name, github, tag: s("tag"), branch: s("branch"), commit });
        }
        packages.sort_by(|a, b| a.name.cmp(&b.name));
        Ok(Lock { packages })
    }

    /// Write only when the bytes change, so a second `add` is the no-op it
    /// claims to be rather than a touched file.
    pub fn save(&self, dir: &Path) -> Result<bool, String> {
        let mut out = String::from(
            "# generated by trantor; run `trantor update` to move a pin\n\
             # edit [deps] in world.toml, not this file\n",
        );
        let mut sorted = self.packages.clone();
        sorted.sort_by(|a, b| a.name.cmp(&b.name));
        for e in &sorted {
            out.push_str("\n[[package]]\n");
            out.push_str(&format!("name = {:?}\n", e.name));
            out.push_str(&format!("github = {:?}\n", e.github));
            if let Some(t) = &e.tag {
                out.push_str(&format!("tag = {t:?}\n"));
            }
            if let Some(b) = &e.branch {
                out.push_str(&format!("branch = {b:?}\n"));
            }
            out.push_str(&format!("commit = {:?}\n", e.commit));
        }
        let p = dir.join(LOCK_FILE);
        if std::fs::read_to_string(&p).is_ok_and(|old| old == out) {
            return Ok(false);
        }
        std::fs::write(&p, out).map_err(|e| format!("write {}: {e}", p.display()))?;
        Ok(true)
    }
}

fn git(args: &[&str], what: &str) -> Result<String, String> {
    let out = Command::new("git")
        .args(args)
        .output()
        .map_err(|e| format!("{what}: spawn git: {e} (is git installed?)"))?;
    if !out.status.success() {
        return Err(format!(
            "{what}: git {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(String::from_utf8_lossy(&out.stdout).into_owned())
}

pub fn url_of(slug: &str) -> String {
    format!("https://github.com/{slug}.git")
}

/// A semver tag's ordering key. `v1.2.0` and `1.2.0` both parse; anything with
/// a prerelease suffix is skipped, because resolving "newest" onto an alpha is
/// never what someone adding a dependency meant.
pub fn semver_key(tag: &str) -> Option<(u64, u64, u64)> {
    let t = tag.strip_prefix('v').unwrap_or(tag);
    if t.contains('-') || t.contains('+') {
        return None;
    }
    let mut it = t.split('.');
    let (a, b, c) = (it.next()?, it.next()?, it.next()?);
    if it.next().is_some() {
        return None;
    }
    Some((a.parse().ok()?, b.parse().ok()?, c.parse().ok()?))
}

/// Parse `git ls-remote --tags` into tag -> commit sha.
///
/// An annotated tag prints twice: `refs/tags/v1` (the tag OBJECT's sha) and
/// `refs/tags/v1^{}` (the commit it points at). The peeled line is the one the
/// lock wants — recording the tag object instead still clones fine, so the bug
/// stays invisible until someone compares the lock against `git log`.
pub fn parse_tags(out: &str) -> BTreeMap<String, String> {
    let mut m: BTreeMap<String, String> = BTreeMap::new();
    let mut peeled: BTreeMap<String, String> = BTreeMap::new();
    for line in out.lines() {
        let Some((sha, r)) = line.split_once('\t') else { continue };
        let Some(name) = r.strip_prefix("refs/tags/") else { continue };
        match name.strip_suffix("^{}") {
            Some(base) => {
                peeled.insert(base.to_string(), sha.to_string());
            }
            None => {
                m.insert(name.to_string(), sha.to_string());
            }
        }
    }
    m.extend(peeled); // the peeled sha wins wherever there is one
    m
}

pub enum Resolved {
    Tag(String, String),
    Branch(String, String),
}

/// The newest semver tag, else the default branch's HEAD (D-U1-3).
pub fn resolve(slug: &str) -> Result<Resolved, String> {
    let url = url_of(slug);
    let tags = parse_tags(&git(&["ls-remote", "--tags", &url], &format!("resolve {slug}"))?);
    let best = tags
        .iter()
        .filter_map(|(t, sha)| semver_key(t).map(|k| (k, t.clone(), sha.clone())))
        .max_by_key(|(k, _, _)| *k);
    if let Some((_, tag, sha)) = best {
        return Ok(Resolved::Tag(tag, sha));
    }
    // No semver tags. `--symref` names the default branch without the API.
    let out = git(&["ls-remote", "--symref", &url, "HEAD"], &format!("resolve {slug}"))?;
    let mut branch = None;
    let mut sha = None;
    for line in out.lines() {
        if let Some(rest) = line.strip_prefix("ref: ") {
            if let Some((r, _)) = rest.split_once('\t') {
                branch = r.strip_prefix("refs/heads/").map(str::to_string);
            }
        } else if let Some((s, r)) = line.split_once('\t') {
            if r.trim() == "HEAD" {
                sha = Some(s.to_string());
            }
        }
    }
    match (branch, sha) {
        (Some(b), Some(s)) => {
            if !tags.is_empty() {
                eprintln!(
                    "trantor: {slug} has {} tag(s) but none parse as semver; pinning {b} HEAD",
                    tags.len()
                );
            }
            Ok(Resolved::Branch(b, s))
        }
        _ => Err(format!(
            "resolve {slug}: the repository has no semver tags and no readable default branch. \
             Is https://github.com/{slug} public and non-empty?"
        )),
    }
}

/// The package's sources at that commit, fetching only if not already cached.
///
/// Fetching by sha rather than cloning a ref is what makes the CI case work: a
/// committed lock names a commit, and `git clone --branch` cannot take one.
/// It also removes the tag-moved hazard entirely — a moved tag cannot change
/// what a sha fetches.
pub fn ensure_cached(slug: &str, commit: &str) -> Result<PathBuf, String> {
    let dir = cache_dir(slug, commit)?;
    if dir.join(".git").is_dir() {
        return Ok(dir);
    }
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).map_err(|e| format!("create {}: {e}", dir.display()))?;
    let d = dir.to_string_lossy().into_owned();
    let url = url_of(slug);
    git(&["-C", &d, "init", "-q"], "fetch")?;
    git(&["-C", &d, "remote", "add", "origin", &url], "fetch")?;
    git(&["-C", &d, "fetch", "-q", "--depth", "1", "origin", commit], &format!("fetch {slug}"))
        .map_err(|e| {
            let _ = std::fs::remove_dir_all(&dir);
            format!("{e}\n(the commit may have been force-pushed away, or the repo made private)")
        })?;
    git(&["-C", &d, "checkout", "-q", "FETCH_HEAD"], "fetch")?;
    // The sha is what we asked for; confirm it is what we got. A tag can move;
    // a checked-out sha that disagrees with the lock cannot be allowed to pass.
    let head = git(&["-C", &d, "rev-parse", "HEAD"], "fetch")?.trim().to_string();
    if head != commit {
        let _ = std::fs::remove_dir_all(&dir);
        return Err(format!("fetch {slug}: asked for {commit}, got {head}"));
    }
    Ok(dir)
}

/// Resolve a `github` dep to its sources: the lock says which commit, the cache
/// holds it, and a cold cache with a committed lock fetches that exact commit.
pub fn github_root(world_dir: &Path, name: &str, slug: &str) -> Result<PathBuf, String> {
    let lock = Lock::load(world_dir)?;
    let Some(e) = lock.get(name) else {
        return Err(format!(
            "dep `{name}` ({slug}) is not in {LOCK_FILE}. Run `trantor add {slug}` to resolve it \
             to a tag and record the commit."
        ));
    };
    if e.github != slug {
        return Err(format!(
            "dep `{name}`: world.toml says `{slug}` but {LOCK_FILE} pins `{}`. Run \
             `trantor update {name}`.",
            e.github
        ));
    }
    ensure_cached(slug, &e.commit)
}

// ---- the commands -----------------------------------------------------------

fn edit_world(dir: &Path, world_file: &str) -> Result<(PathBuf, toml_edit::DocumentMut), String> {
    let p = dir.join(world_file);
    let text = std::fs::read_to_string(&p).map_err(|e| format!("read {}: {e}", p.display()))?;
    let doc = text
        .parse::<toml_edit::DocumentMut>()
        .map_err(|e| format!("parse {}: {e}", p.display()))?;
    Ok((p, doc))
}

/// A github package resolved to a commit and fetched into the cache.
pub struct Fetched {
    pub slug: String,
    /// What the package calls itself — the name a `[deps]` entry uses.
    pub name: String,
    pub tag: Option<String>,
    pub branch: Option<String>,
    pub commit: String,
}

/// Resolve `<org>/<repo>` to a tag (or the default branch's HEAD) and fetch
/// it. Touches no project file.
pub fn fetch(slug: &str) -> Result<Fetched, String> {
    if slug.split('/').count() != 2 || slug.split('/').any(|p| p.is_empty()) {
        return Err(format!("add: expected <org>/<repo>, got {slug:?}"));
    }
    let resolved = resolve(slug)?;
    let (tag, branch, commit) = match &resolved {
        Resolved::Tag(t, c) => (Some(t.clone()), None, c.clone()),
        Resolved::Branch(b, c) => (None, Some(b.clone()), c.clone()),
    };
    let root = ensure_cached(slug, &commit)?;
    // The dependency names itself; the repo name is only a fallback.
    let pkg_file = root.join("package.toml");
    let name = std::fs::read_to_string(&pkg_file)
        .map_err(|e| {
            format!(
                "add {slug}: read {}: {e}\nA trantor dependency is a package: it needs a \
                 package.toml at its root declaring what it provides.",
                pkg_file.display()
            )
        })
        .and_then(|t| {
            toml::from_str::<crate::manifest::Package>(&t)
                .map_err(|e| format!("parse {}: {e}", pkg_file.display()))
        })?
        .package
        .name;
    Ok(Fetched { slug: slug.to_string(), name, tag, branch, commit })
}

/// Write the one `[deps]` line into `manifest` (a world.toml or package.toml
/// under `dir`) and pin it in `dir`'s lock. Validation, and undoing this when
/// it fails, is the caller's.
pub fn record(dir: &Path, manifest: &str, dep_name: &str, f: &Fetched) -> Result<bool, String> {
    let (p, mut doc) = edit_world(dir, manifest)?;
    let deps = doc["deps"].or_insert(toml_edit::table());
    if let Some(t) = deps.as_table_mut() {
        t.set_implicit(false);
    }
    let mut inline = toml_edit::InlineTable::new();
    inline.insert("github", f.slug.as_str().into());
    deps[dep_name] = toml_edit::value(inline);
    std::fs::write(&p, doc.to_string()).map_err(|e| format!("write {}: {e}", p.display()))?;

    let mut lock = Lock::load(dir)?;
    lock.packages.retain(|e| e.name != dep_name);
    lock.packages.push(Entry {
        name: dep_name.to_string(),
        github: f.slug.clone(),
        tag: f.tag.clone(),
        branch: f.branch.clone(),
        commit: f.commit.clone(),
    });
    lock.save(dir)
}

/// `trantor update [<name>]` — move a pin. Without this the lock's own header
/// tells the user to edit a file that cannot express a version.
pub fn update(dir: &Path, world_file: &str, only: Option<&str>) -> Result<(), String> {
    let world = crate::manifest::load_world_raw(dir, world_file)?;
    let mut lock = Lock::load(dir)?;
    let mut moved = 0;
    let mut seen = 0;
    for (name, dep) in &world.deps {
        if only.is_some_and(|o| o != name) {
            continue;
        }
        let DepSource::GitHub(slug) = dep.source(name)? else { continue };
        seen += 1;
        let resolved = resolve(&slug)?;
        let (tag, branch, commit) = match resolved {
            Resolved::Tag(t, c) => (Some(t), None, c),
            Resolved::Branch(b, c) => (None, Some(b), c),
        };
        let before = lock.get(name).map(|e| e.commit.clone());
        if before.as_deref() == Some(commit.as_str()) {
            eprintln!("trantor: `{name}` is already at {}", &commit[..12.min(commit.len())]);
            continue;
        }
        ensure_cached(&slug, &commit)?;
        lock.packages.retain(|e| e.name != *name);
        lock.packages.push(Entry { name: name.clone(), github: slug, tag: tag.clone(), branch, commit: commit.clone() });
        moved += 1;
        eprintln!(
            "trantor: `{name}` {} -> {}{}",
            before.as_deref().map_or("(unpinned)".into(), |c| c[..12.min(c.len())].to_string()),
            &commit[..12.min(commit.len())],
            tag.map_or(String::new(), |t| format!(" ({t})"))
        );
    }
    if let Some(o) = only {
        if seen == 0 {
            return Err(format!("update: no github dep named `{o}` in {world_file}"));
        }
    } else if seen == 0 {
        return Err(format!("update: {world_file} has no github deps to update"));
    }
    lock.save(dir)?;
    eprintln!("trantor: {moved} of {seen} dep(s) moved");
    Ok(())
}

/// `trantor remove <name>` — drop the dep and its pin.
pub fn remove(dir: &Path, world_file: &str, name: &str) -> Result<(), String> {
    let (p, mut doc) = edit_world(dir, world_file)?;
    let had = doc
        .get_mut("deps")
        .and_then(|d| d.as_table_like_mut())
        .map(|t| t.remove(name).is_some())
        .unwrap_or(false);
    if !had {
        return Err(format!("remove: {world_file} has no dep named `{name}`"));
    }
    if doc.get("deps").and_then(|d| d.as_table_like()).is_some_and(|t| t.is_empty()) {
        doc.remove("deps");
    }
    std::fs::write(&p, doc.to_string()).map_err(|e| format!("write {}: {e}", p.display()))?;
    let mut lock = Lock::load(dir)?;
    lock.packages.retain(|e| e.name != name);
    lock.save(dir)?;
    eprintln!("trantor: removed `{name}`");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn semver_key_accepts_both_spellings_and_skips_prereleases() {
        assert_eq!(semver_key("v1.2.3").unwrap(), (1, 2, 3));
        assert_eq!(semver_key("0.21.0").unwrap(), (0, 21, 0));
        assert!(semver_key("v1.2.3-rc1").is_none(), "a prerelease is never what `add` meant");
        assert!(semver_key("release-2024").is_none());
        assert!(semver_key("v1.2").is_none());
    }

    #[test]
    fn newest_wins_numerically_not_lexically() {
        let mut v: Vec<_> = ["v1.9.0", "v1.10.0", "v1.2.0"].iter().map(|t| (semver_key(t).unwrap(), *t)).collect();
        v.sort();
        assert_eq!(v.last().unwrap().1, "v1.10.0", "lexical order would pick v1.9.0");
    }

    #[test]
    fn an_annotated_tag_resolves_to_the_commit_not_the_tag_object() {
        // The peeled `^{}` line is the commit; recording the tag object still
        // clones fine, so this bug hides until someone reads the lock.
        let out = "aaa1\trefs/tags/v1.0.0\nbbb2\trefs/tags/v1.0.0^{}\nccc3\trefs/tags/v0.9.0\n";
        let tags = parse_tags(out);
        assert_eq!(tags.get("v1.0.0").unwrap(), "bbb2");
        assert_eq!(tags.get("v0.9.0").unwrap(), "ccc3");
        assert!(!tags.contains_key("v1.0.0^{}"));
    }

    #[test]
    fn the_lock_round_trips_and_a_rewrite_is_a_no_op() {
        let d = std::env::temp_dir().join(format!("trantor-lock-{}", std::process::id()));
        std::fs::create_dir_all(&d).unwrap();
        let l = Lock {
            packages: vec![Entry {
                name: "base".into(),
                github: "org/repo".into(),
                tag: Some("v1.0.0".into()),
                branch: None,
                commit: "abc123".into(),
            }],
        };
        assert!(l.save(&d).unwrap(), "first write changes the file");
        let back = Lock::load(&d).unwrap();
        assert_eq!(back.packages, l.packages);
        assert!(!back.save(&d).unwrap(), "a second save must be a no-op");
        std::fs::remove_dir_all(&d).ok();
    }

    /// D-U1-3: no code path may reach api.github.com. The property is easy to
    /// lose to one convenient call, so it is asserted rather than intended.
    #[test]
    fn nothing_here_talks_to_the_github_api() {
        let src = include_str!("registry.rs");
        // Strip comments: this module DESCRIBES the host it avoids, and the
        // check is about what the code reaches, not what the prose says.
        let body: String = src
            .split("mod tests")
            .next()
            .unwrap()
            .lines()
            .filter(|l| !l.trim_start().starts_with("//"))
            .collect::<Vec<_>>()
            .join("\n");
        assert!(!body.contains("api.github.com"), "the no-token property is gone");
        assert!(body.contains("https://github.com/"), "positive control: the plain host is used");
    }
}
