//! The generated service shim, `abi/src/services.rs` (D-H7-7): everything the
//! driver needs to talk to its service components, emitted from the resolved
//! world so the driver's own code never names a component.
//!
//! Per service `<c>` with modules `M` / `MEvent` / `MEnv` the shim declares the
//! component's contract — `hematite__<c>__init(*const HostCtx)`,
//! `__cmd(request, M) -> RocList<Answer<MEvent>>` (the route key lives in the
//! service's own payload and comes back in each `Answer`; D-H7-17),
//! `__complete(token) -> RocList<Completion<MEvent>>` (a wake yields 0..n
//! completions, in order — a coalesced no-op says nothing, a dying child's
//! last lines precede its exit; D-H7-20), `__env() -> MEnv`,
//! `__gate(name, argv, out) -> i32` — and gives the driver:
//!   - `init(wake, measure_text, groups)`: hands every component its `HostCtx`
//!     (D8) — wake, text measure (D-H7-22), and the group registry a document
//!     service publishes page draw lists through (D-H7-11);
//!   - `dispatch(&mut cmd, request)`: one arm per wrapper variant,
//!     moving the payload to the component and wrapping its answers back into
//!     the world's `Event`; `None` for a core variant (the driver's own);
//!   - `on_wake(id, token)`: the runtime-thread half of D9 — the component's
//!     `complete` builds the Roc values, the shim wraps each;
//!   - `env_<m>()`: each env block, for the driver's per-frame `Env` assembly;
//!   - `gate(name, argv) -> Option<GateResult>`: the chain, components before
//!     the driver (D-H7-8); a hook answers with a code AND text (D-H7-40).
//!
//! Measured in P0 (`tests/golden/im-services`) by hand; this generates the same
//! text from the manifest.

use crate::resolve::{Resolved, Service};
use crate::splice::snake_case;

const GEN_RS: &str = "// GENERATED BY hematite — do not edit. Regenerate with `hematite compose`.";

/// The `abi/src/services.rs` text for a world, or `None` when it has no
/// service components (the shim references `Event`, which a service-less
/// driver need not ship) — unless the driver asks for it anyway
/// (`services_shim`, D-H7-33), in which case every call is a no-op.
pub fn services_rs(r: &Resolved, always: bool) -> Option<String> {
    if r.services.is_empty() && !always {
        return None;
    }
    let mut s = String::new();
    s.push_str(GEN_RS);
    s.push_str(
        "\n//! The service contract shim (D-H7-7): the driver's view of every service\n\
         //! component in this world. See hematite's src/services.rs for the shape.\n\
         use super::*;\nuse core::ffi::c_void;\nuse std::sync::OnceLock;\n\n",
    );
    s.push_str(CONTRACT_TYPES);
    for (i, svc) in r.services.iter().enumerate() {
        s.push_str(&component_decls(svc, i as u32 + 1));
    }
    s.push_str(&init_fn(&r.services));
    s.push_str(&dispatch_fn(&r.services));
    s.push_str(&on_wake_fn(&r.services));
    s.push_str(&env_fns(&r.services));
    s.push_str(&gate_fn(&r.services));
    Some(s)
}

const CONTRACT_TYPES: &str = r#"/// D8's `HostCtx`: what the driver hands each component at `init` — the
/// driver's capabilities, as C-ABI function pointers.
#[repr(C)]
pub struct HostCtx {
    pub component_id: u32,
    /// Callable from any thread; the token is component-owned (D9) and comes
    /// back to the component through `complete` on the runtime thread.
    pub wake: extern "C" fn(u32, *mut c_void),
    /// Measure `len` bytes of UTF-8 at `ptr` in the driver's font `font`, in
    /// the driver's width units (D-H7-22: a service sizing text — dbx's
    /// columns — cannot reach the renderer's metrics any other way). Callable
    /// from any thread.
    pub measure_text: extern "C" fn(*const u8, usize, u16) -> i32,
    /// Publish a host-built draw list (a `Scene`) under a driver-minted handle
    /// at `generation`, and get the handle back (D-H7-11, P8: a document
    /// service's page group). The pointer is BORROWED for the duration of the
    /// call — the driver copies what it keeps — so the component stays the
    /// owner and nothing Rust-allocated changes hands. Runtime thread.
    pub register_group: extern "C" fn(*const c_void, u32) -> i32,
    /// Forget a published group; the handle names nothing afterwards.
    pub release_group: extern "C" fn(i32),
}

/// A synchronous answer to a wrapper command, in the component's own event type.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Answer<E: Copy> {
    pub route_key: RocStr,
    pub event: E,
}

/// One of the completions `complete` returns for a token the component woke
/// the driver with (zero or more per wake, in order; D-H7-20).
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Completion<E: Copy> {
    pub request: u64,
    pub route_key: RocStr,
    pub event: E,
}

/// What a gate hook answered: its exit code, and whatever text it wrote.
///
/// A hook exists to be ASKED things — "how many requests are outstanding?",
/// "what did the app write?" — and an `i32` cannot carry an answer, so before
/// this a component that had one smuggled it out through a file named by an
/// environment variable (D-H7-40). The hook writes into the `*mut RocStr` the
/// chain passes it, transferring ownership; the chain copies the text and
/// releases it. A hook with nothing to say leaves it alone and `out` is empty.
pub struct GateResult {
    pub code: i32,
    pub out: String,
}

/// A component's gate hook, as the chain below calls it. `C-unwind` natively,
/// `C` on wasm32 — see the contract declarations' note.
#[cfg(not(target_arch = "wasm32"))]
type GateFn = unsafe extern "C-unwind" fn(RocStr, RocList<RocStr>, *mut RocStr) -> i32;
#[cfg(target_arch = "wasm32")]
type GateFn = unsafe extern "C" fn(RocStr, RocList<RocStr>, *mut RocStr) -> i32;

static WAKE: OnceLock<fn(u32, *mut c_void)> = OnceLock::new();
static MEASURE: OnceLock<extern "C" fn(*const u8, usize, u16) -> i32> = OnceLock::new();
static GROUPS: OnceLock<Groups> = OnceLock::new();

/// The driver's group registry, as two C-ABI entry points.
#[derive(Clone, Copy)]
pub struct Groups {
    pub register: extern "C" fn(*const c_void, u32) -> i32,
    pub release: extern "C" fn(i32),
}

/// The one `wake` every component is handed: forwards to the driver's loop.
extern "C" fn courier(component_id: u32, token: *mut c_void) {
    if let Some(f) = WAKE.get() {
        f(component_id, token);
    }
}

/// The one `measure_text` every component is handed: the driver's, or 0.
extern "C" fn measure(ptr: *const u8, len: usize, font: u16) -> i32 {
    match MEASURE.get() {
        Some(f) => f(ptr, len, font),
        None => 0,
    }
}

/// The one `register_group` every component is handed: the driver's, or -1
/// (a driver with no group registry publishes nothing).
extern "C" fn register_group(scene: *const c_void, generation: u32) -> i32 {
    match GROUPS.get() {
        Some(g) => (g.register)(scene, generation),
        None => -1,
    }
}

extern "C" fn release_group(handle: i32) {
    if let Some(g) = GROUPS.get() {
        (g.release)(handle);
    }
}

"#;

fn upper(name: &str) -> String {
    snake_case(name).to_ascii_uppercase()
}

fn component_decls(svc: &Service, id: u32) -> String {
    let p = svc.symbol_prefix();
    let m = &svc.module;
    let mut s = format!(
        "pub const {id_name}_ID: u32 = {id};\nstatic CTX_{id_name}: HostCtx = HostCtx {{ component_id: {id}, wake: courier, measure_text: measure, register_group, release_group }};\n",
        id_name = upper(m)
    );
    // The contract's declarations, once; the ABI string around them twice.
    let mut decls = format!("    fn {p}init(ctx: *const HostCtx);\n");
    match &svc.event_module {
        Some(ev) => {
            decls.push_str(&format!(
                "    fn {p}cmd(request: u64, cmd: {m}) -> RocList<Answer<{ev}>>;\n\
                 \x20   fn {p}complete(token: *mut c_void) -> RocList<Completion<{ev}>>;\n"
            ));
        }
        None => decls.push_str(&format!("    fn {p}cmd(request: u64, cmd: {m});\n")),
    }
    if let Some(env) = &svc.env_module {
        decls.push_str(&format!("    fn {p}env() -> {env};\n"));
    }
    decls.push_str(&format!("    fn {p}gate(name: RocStr, argv: RocList<RocStr>, out: *mut RocStr) -> i32;\n"));
    // `C-unwind` natively (H0d: a component's panic reaches the driver's
    // catch_unwind); plain `C` on wasm32, where nothing unwinds and a
    // `C-unwind` call under immediate-abort panics is lowered to a wasm
    // exception-handling landing pad — which roc's link does not enable
    // (measured: `catch_all` in the DOM driver's frame, D-H7-32).
    s.push_str(&format!(
        "#[cfg(not(target_arch = \"wasm32\"))]\nunsafe extern \"C-unwind\" {{\n{decls}}}\n\
         #[cfg(target_arch = \"wasm32\")]\nunsafe extern \"C\" {{\n{decls}}}\n\n"
    ));
    s
}

fn init_fn(services: &[Service]) -> String {
    let mut s = String::from(
        "/// Install the driver's wake sink, text measurer and group registry\n\
         /// (`None` for a driver that publishes no draw lists), and hand every\n\
         /// component its `HostCtx`. Call once, before the first drain.\n\
         pub fn init(wake: fn(u32, *mut c_void), measure_text: extern \"C\" fn(*const u8, usize, u16) -> i32, groups: Option<Groups>) {\n\
         \x20   let _ = WAKE.set(wake);\n    let _ = MEASURE.set(measure_text);\n    if let Some(g) = groups {\n        let _ = GROUPS.set(g);\n    }\n",
    );
    if !services.is_empty() {
        s.push_str("    unsafe {\n");
        for svc in services {
            s.push_str(&format!("        {}init(&CTX_{});\n", svc.symbol_prefix(), upper(&svc.module)));
        }
        s.push_str("    }\n");
    }
    s.push_str("}\n\n");
    s
}

/// The `Event` wrapping for a service's event value — through `tagged::build`,
/// which is right on both pointer widths (a struct literal names the 64-bit
/// union only; wasm32's payload is a byte array).
fn wrap_event(svc: &Service, value: &str) -> String {
    format!("unsafe {{ tagged::build(|e: &mut Event| e.tag = EventTag::{}, {value}) }}", svc.module)
}

fn dispatch_fn(services: &[Service]) -> String {
    let mut s = String::from(
        "/// Dispatch one drained command to its service. `None` for a core variant\n\
         /// (the driver handles those itself; the payload is untouched). Otherwise\n\
         /// the payload is MOVED to the component and its answers come back routed:\n\
         /// (route_key, event) pairs the driver feeds to `route`. `request` is the\n\
         /// host-minted id; the route key is the service's own (D-H7-17).\n\
         pub fn dispatch(cmd: &mut Cmd, request: u64) -> Option<Vec<(RocStr, Event)>> {\n",
    );
    if services.is_empty() {
        s.push_str("    let _ = (cmd, request);\n    None\n}\n\n");
        return s;
    }
    s.push_str("    let host = host();\n    match cmd.tag {\n");
    for svc in services {
        let p = svc.symbol_prefix();
        let field = snake_case(&svc.module);
        s.push_str(&format!(
            "        CmdTag::{m} => {{\n            let payload = unsafe {{ cmd.take_payload_{field}_unchecked() }};\n",
            m = svc.module
        ));
        if svc.event_module.is_some() {
            s.push_str(&format!(
                "            let answers = unsafe {{ {p}cmd(request, payload) }};\n\
                 \x20           let mut out = Vec::with_capacity(answers.len());\n\
                 \x20           for a in answers.as_slice() {{\n\
                 \x20               out.push((a.route_key, {}));\n\
                 \x20           }}\n\
                 \x20           unsafe {{ answers.decref(host) }}; // shallow: each answer was copied out\n\
                 \x20           Some(out)\n        }}\n",
                wrap_event(svc, "a.event")
            ));
        } else {
            s.push_str(&format!(
                "            unsafe {{ {p}cmd(request, payload) }};\n            Some(Vec::new())\n        }}\n"
            ));
        }
    }
    s.push_str("        #[allow(unreachable_patterns)]\n        _ => None,\n    }\n}\n\n");
    s
}

fn on_wake_fn(services: &[Service]) -> String {
    let mut s = String::from(
        "/// The runtime-thread half of a wake (D9): the component turns its token\n\
         /// into zero or more Roc events, in order (D-H7-20); the shim wraps each.\n\
         /// Empty for an unknown component id.\n\
         pub fn on_wake(component_id: u32, token: *mut c_void) -> Vec<(u64, RocStr, Event)> {\n",
    );
    if !services.iter().any(|s| s.event_module.is_some()) {
        s.push_str("    let _ = (component_id, token);\n    Vec::new()\n}\n\n");
        return s;
    }
    s.push_str("    let host = host();\n    match component_id {\n");
    for svc in services.iter().filter(|s| s.event_module.is_some()) {
        s.push_str(&format!(
            "        {id}_ID => {{\n            let done = unsafe {{ {p}complete(token) }};\n\
             \x20           let out: Vec<(u64, RocStr, Event)> = done.as_slice().iter().map(|c| (c.request, c.route_key, {ev})).collect();\n\
             \x20           unsafe {{ done.decref(host) }}; // shallow: each completion was copied out\n\
             \x20           out\n        }}\n",
            id = upper(&svc.module),
            p = svc.symbol_prefix(),
            ev = wrap_event(svc, "c.event")
        ));
    }
    s.push_str("        _ => Vec::new(),\n    }\n}\n\n");
    s
}

fn env_fns(services: &[Service]) -> String {
    let mut s = String::new();
    for svc in services {
        if let Some(env) = &svc.env_module {
            s.push_str(&format!(
                "/// `{env}`: the `{}` block of `Env`, read once per frame.\n\
                 pub fn env_{field}() -> {env} {{\n    unsafe {{ {p}env() }}\n}}\n\n",
                snake_case(&svc.module),
                field = snake_case(&svc.module),
                p = svc.symbol_prefix()
            ));
        }
    }
    s
}

fn gate_fn(services: &[Service]) -> String {
    let mut s = String::from(
        "/// The gate chain (D-H7-8): ask every component before the driver's own\n\
         /// arms. `Some(..)` from the first component that claims `name`.\n\
         pub fn gate(name: &str, argv: &[String]) -> Option<GateResult> {\n",
    );
    if services.is_empty() {
        s.push_str("    let _ = (name, argv);\n    None\n}\n");
        return s;
    }
    s.push_str("    let host = host();\n    let gates: [GateFn; N_SERVICES] = [\n");
    for svc in services {
        s.push_str(&format!("        {}gate,\n", svc.symbol_prefix()));
    }
    s.push_str(
        "    ];\n    for g in gates {\n        let args: Vec<RocStr> = argv.iter().map(|a| RocStr::from_str(a, host)).collect();\n\
         \x20       let list = unsafe { RocList::from_slice(&args, host) };\n\
         \x20       // Empty is the small-string form, so this allocates nothing; a hook\n\
         \x20       // that answers overwrites it and hands us the allocation.\n\
         \x20       let mut out = RocStr::from_str(\"\", host);\n\
         \x20       let rc = unsafe { g(RocStr::from_str(name, host), list, &mut out) };\n\
         \x20       let text = out.as_str().to_string();\n\
         \x20       unsafe { out.decref(host) };\n\
         \x20       if rc != -1 {\n            return Some(GateResult { code: rc, out: text });\n        }\n    }\n    None\n}\n",
    );
    s.replace("N_SERVICES", &services.len().to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    fn world_with(services: Vec<Service>) -> Resolved {
        Resolved {
            hosted: vec![],
            archive_order: vec![],
            imports: vec![],
            driver: "d".into(),
            interface_modules: BTreeMap::new(),
            roc_impls: vec![],
            services,
            extra_modules: vec![],
        }
    }

    #[test]
    fn no_services_emits_nothing() {
        assert!(services_rs(&world_with(vec![]), false).is_none());
        // A driver that asks for the shim anyway gets no-op entry points.
        let empty = services_rs(&world_with(vec![]), true).unwrap();
        assert!(empty.contains("pub fn dispatch(") && empty.contains("let _ = (cmd, request);"));
        assert!(empty.contains("let _ = (name, argv);"));
    }

    #[test]
    fn declares_contract_and_wraps_events() {
        let r = world_with(vec![
            Service { component: "svc-echo".into(), module: "Echo".into(), event_module: Some("EchoEvent".into()), env_module: None },
            Service { component: "svc-tick".into(), module: "Tick".into(), event_module: Some("TickEvent".into()), env_module: Some("TickEnv".into()) },
        ]);
        let s = services_rs(&r, false).unwrap();
        assert!(s.contains("fn hematite__svc_echo__cmd(request: u64, cmd: Echo) -> RocList<Answer<EchoEvent>>;"));
        assert!(s.contains("fn hematite__svc_tick__env() -> TickEnv;"));
        assert!(s.contains("CmdTag::Echo => {"));
        assert!(s.contains("tagged::build(|e: &mut Event| e.tag = EventTag::Tick, c.event)"));
        assert!(s.contains("pub fn env_tick() -> TickEnv"));
        assert!(s.contains("[GateFn; 2]"));
        // The gate chain carries an answer out, not just an exit code (D-H7-40).
        assert!(s.contains("-> Option<GateResult>") && s.contains("GateResult { code: rc, out: text }"));
        assert!(s.contains("list, &mut out)"));
        assert!(!s.contains("N_SERVICES"));
    }
}
