//! The generated service shim, `abi/src/services.rs` (D-H7-7): everything the
//! driver needs to talk to its service components, emitted from the resolved
//! world so the driver's own code never names a component.
//!
//! Per service `<c>` with modules `M` / `MEvent` / `MEnv` the shim declares the
//! component's contract — `hematite__<c>__init(*const HostCtx)`,
//! `__cmd(request, route_key, M) -> RocList<Answer<MEvent>>`,
//! `__complete(token) -> Completion<MEvent>`, `__env() -> MEnv`,
//! `__gate(name, argv) -> i32` — and gives the driver:
//!   - `init(wake)`: hands every component its `HostCtx` (D8);
//!   - `dispatch(&mut cmd, request, route_key)`: one arm per wrapper variant,
//!     moving the payload to the component and wrapping its answers back into
//!     the world's `Event`; `None` for a core variant (the driver's own);
//!   - `on_wake(id, token)`: the runtime-thread half of D9 — the component's
//!     `complete` builds the Roc value, the shim wraps it;
//!   - `env_<m>()`: each env block, for the driver's per-frame `Env` assembly;
//!   - `gate(name, argv)`: the chain, components before the driver (D-H7-8).
//!
//! Measured in P0 (`tests/golden/im-services`) by hand; this generates the same
//! text from the manifest.

use crate::resolve::{Resolved, Service};
use crate::splice::snake_case;

const GEN_RS: &str = "// GENERATED BY hematite — do not edit. Regenerate with `hematite compose`.";

/// The `abi/src/services.rs` text for a world, or `None` when it has no
/// service components (the shim references `Event`, which a service-less
/// driver need not ship).
pub fn services_rs(r: &Resolved) -> Option<String> {
    if r.services.is_empty() {
        return None;
    }
    let mut s = String::new();
    s.push_str(GEN_RS);
    s.push_str(
        "\n//! The service contract shim (D-H7-7): the driver's view of every service\n\
         //! component in this world. See hematite's src/services.rs for the shape.\n\
         use super::*;\nuse core::ffi::c_void;\nuse core::mem::ManuallyDrop;\nuse std::sync::OnceLock;\n\n",
    );
    s.push_str(CONTRACT_TYPES);
    for (i, svc) in r.services.iter().enumerate() {
        s.push_str(&component_decls(svc, i as u32 + 1));
    }
    s.push_str(&init_fn(&r.services));
    s.push_str(&dispatch_fn(&r.services));
    s.push_str(&on_wake_fn(&r.services));
    s.push_str(&env_fns(&r.services));
    s.push_str(&gate_fn(&r.services));
    Some(s)
}

const CONTRACT_TYPES: &str = r#"/// D8's `HostCtx`: what the driver hands each component at `init`.
#[repr(C)]
pub struct HostCtx {
    pub component_id: u32,
    /// Callable from any thread; the token is component-owned (D9) and comes
    /// back to the component through `complete` on the runtime thread.
    pub wake: extern "C" fn(u32, *mut c_void),
}

/// A synchronous answer to a wrapper command, in the component's own event type.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Answer<E: Copy> {
    pub route_key: RocStr,
    pub event: E,
}

/// What `complete` returns for a token the component woke the driver with.
#[repr(C)]
pub struct Completion<E> {
    pub request: u64,
    pub route_key: RocStr,
    pub event: E,
}

static WAKE: OnceLock<fn(u32, *mut c_void)> = OnceLock::new();

/// The one `wake` every component is handed: forwards to the driver's loop.
extern "C" fn courier(component_id: u32, token: *mut c_void) {
    if let Some(f) = WAKE.get() {
        f(component_id, token);
    }
}

"#;

fn upper(name: &str) -> String {
    snake_case(name).to_ascii_uppercase()
}

fn component_decls(svc: &Service, id: u32) -> String {
    let p = svc.symbol_prefix();
    let m = &svc.module;
    let mut s = format!(
        "pub const {id_name}_ID: u32 = {id};\nstatic CTX_{id_name}: HostCtx = HostCtx {{ component_id: {id}, wake: courier }};\n\
         unsafe extern \"C-unwind\" {{\n    fn {p}init(ctx: *const HostCtx);\n",
        id_name = upper(m)
    );
    match &svc.event_module {
        Some(ev) => {
            s.push_str(&format!(
                "    fn {p}cmd(request: u64, route_key: RocStr, cmd: {m}) -> RocList<Answer<{ev}>>;\n\
                 \x20   fn {p}complete(token: *mut c_void) -> Completion<{ev}>;\n"
            ));
        }
        None => s.push_str(&format!("    fn {p}cmd(request: u64, route_key: RocStr, cmd: {m});\n")),
    }
    if let Some(env) = &svc.env_module {
        s.push_str(&format!("    fn {p}env() -> {env};\n"));
    }
    s.push_str(&format!("    fn {p}gate(name: RocStr, argv: RocList<RocStr>) -> i32;\n}}\n\n"));
    s
}

fn init_fn(services: &[Service]) -> String {
    let mut s = String::from(
        "/// Install the driver's wake sink and hand every component its `HostCtx`.\n\
         /// Call once, before the first drain.\n\
         pub fn init(wake: fn(u32, *mut c_void)) {\n    let _ = WAKE.set(wake);\n    unsafe {\n",
    );
    for svc in services {
        s.push_str(&format!("        {}init(&CTX_{});\n", svc.symbol_prefix(), upper(&svc.module)));
    }
    s.push_str("    }\n}\n\n");
    s
}

/// The `Event` wrapping for a service's event value.
fn wrap_event(svc: &Service, value: &str) -> String {
    let field = snake_case(&svc.module);
    format!(
        "Event {{ payload: EventPayload {{ {field}: ManuallyDrop::new({value}) }}, tag: EventTag::{} }}",
        svc.module
    )
}

fn dispatch_fn(services: &[Service]) -> String {
    let mut s = String::from(
        "/// Dispatch one drained command to its service. `None` for a core variant\n\
         /// (the driver handles those itself; the payload is untouched). Otherwise\n\
         /// the payload is MOVED to the component and its answers come back routed:\n\
         /// (route_key, event) pairs the driver feeds to `route`.\n\
         pub fn dispatch(cmd: &mut Cmd, request: u64, route_key: &str) -> Option<Vec<(RocStr, Event)>> {\n\
         \x20   let host = host();\n    match cmd.tag {\n",
    );
    for svc in services {
        let p = svc.symbol_prefix();
        let field = snake_case(&svc.module);
        s.push_str(&format!(
            "        CmdTag::{m} => {{\n            let payload = unsafe {{ cmd.take_payload_{field}_unchecked() }};\n\
             \x20           let key = RocStr::from_str(route_key, host);\n",
            m = svc.module
        ));
        if svc.event_module.is_some() {
            s.push_str(&format!(
                "            let answers = unsafe {{ {p}cmd(request, key, payload) }};\n\
                 \x20           let mut out = Vec::with_capacity(answers.len());\n\
                 \x20           for a in answers.as_slice() {{\n\
                 \x20               out.push((a.route_key, {}));\n\
                 \x20           }}\n\
                 \x20           unsafe {{ answers.decref(host) }}; // shallow: each answer was copied out\n\
                 \x20           Some(out)\n        }}\n",
                wrap_event(svc, "a.event")
            ));
        } else {
            s.push_str(&format!(
                "            unsafe {{ {p}cmd(request, key, payload) }};\n            Some(Vec::new())\n        }}\n"
            ));
        }
    }
    s.push_str("        #[allow(unreachable_patterns)]\n        _ => None,\n    }\n}\n\n");
    s
}

fn on_wake_fn(services: &[Service]) -> String {
    let mut s = String::from(
        "/// The runtime-thread half of a wake (D9): the component turns its token\n\
         /// into a Roc event; the shim wraps it. `None` for an unknown component id.\n\
         pub fn on_wake(component_id: u32, token: *mut c_void) -> Option<(u64, RocStr, Event)> {\n    match component_id {\n",
    );
    for svc in services.iter().filter(|s| s.event_module.is_some()) {
        s.push_str(&format!(
            "        {id}_ID => {{\n            let c = unsafe {{ {p}complete(token) }};\n\
             \x20           Some((c.request, c.route_key, {ev}))\n        }}\n",
            id = upper(&svc.module),
            p = svc.symbol_prefix(),
            ev = wrap_event(svc, "c.event")
        ));
    }
    s.push_str("        _ => None,\n    }\n}\n\n");
    s
}

fn env_fns(services: &[Service]) -> String {
    let mut s = String::new();
    for svc in services {
        if let Some(env) = &svc.env_module {
            s.push_str(&format!(
                "/// `{env}`: the `{}` block of `Env`, read once per frame.\n\
                 pub fn env_{field}() -> {env} {{\n    unsafe {{ {p}env() }}\n}}\n\n",
                snake_case(&svc.module),
                field = snake_case(&svc.module),
                p = svc.symbol_prefix()
            ));
        }
    }
    s
}

fn gate_fn(services: &[Service]) -> String {
    let mut s = String::from(
        "/// The gate chain (D-H7-8): ask every component before the driver's own\n\
         /// arms. `Some(rc)` from the first component that claims `name`.\n\
         pub fn gate(name: &str, argv: &[String]) -> Option<i32> {\n    let host = host();\n\
         \x20   let gates: [unsafe extern \"C-unwind\" fn(RocStr, RocList<RocStr>) -> i32; N_SERVICES] = [\n",
    );
    for svc in services {
        s.push_str(&format!("        {}gate,\n", svc.symbol_prefix()));
    }
    s.push_str(
        "    ];\n    for g in gates {\n        let args: Vec<RocStr> = argv.iter().map(|a| RocStr::from_str(a, host)).collect();\n\
         \x20       let list = unsafe { RocList::from_slice(&args, host) };\n\
         \x20       let rc = unsafe { g(RocStr::from_str(name, host), list) };\n\
         \x20       if rc != -1 {\n            return Some(rc);\n        }\n    }\n    None\n}\n",
    );
    s.replace("N_SERVICES", &services.len().to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    fn world_with(services: Vec<Service>) -> Resolved {
        Resolved {
            hosted: vec![],
            archive_order: vec![],
            imports: vec![],
            driver: "d".into(),
            interface_modules: BTreeMap::new(),
            roc_impls: vec![],
            services,
            extra_modules: vec![],
        }
    }

    #[test]
    fn no_services_emits_nothing() {
        assert!(services_rs(&world_with(vec![])).is_none());
    }

    #[test]
    fn declares_contract_and_wraps_events() {
        let r = world_with(vec![
            Service { component: "svc-echo".into(), module: "Echo".into(), event_module: Some("EchoEvent".into()), env_module: None },
            Service { component: "svc-tick".into(), module: "Tick".into(), event_module: Some("TickEvent".into()), env_module: Some("TickEnv".into()) },
        ]);
        let s = services_rs(&r).unwrap();
        assert!(s.contains("fn hematite__svc_echo__cmd(request: u64, route_key: RocStr, cmd: Echo) -> RocList<Answer<EchoEvent>>;"));
        assert!(s.contains("fn hematite__svc_tick__env() -> TickEnv;"));
        assert!(s.contains("CmdTag::Echo => {"));
        assert!(s.contains("EventPayload { tick: ManuallyDrop::new(c.event) }, tag: EventTag::Tick }"));
        assert!(s.contains("pub fn env_tick() -> TickEnv"));
        assert!(s.contains("fn(RocStr, RocList<RocStr>) -> i32; 2]"));
        assert!(!s.contains("N_SERVICES"));
    }
}
